### ISSUE TITLE
Proposal: Room owner addition/deletion should be voted for

### ISSUE THREAD

**Issue by benjamingr** [JavaScriptRoom/culture#1]
I propose that any future room owner additions and removals should be voted on. 

This worked out well when we had meetings.

**Comment by kendfrey** [comment]
How will this be done? Via an issue on this repo, with 24h to vote?

**Comment by MadaraUchiha** [comment]
@kendfrey SGTM :+1:

**Comment by AmaanC** [comment]
Sounds good.

I'm for listening to the majority of votes. No veto privileges or anything of that sort.

Also +1 to doing it on this repo.

**Comment by rlemon** [comment]
I think any votes should be longer than 24 hours. You (Kendall) and I are here daily.. not all RO's share that privilege. I would think a minimum of 72 hours would be fair.

**Comment by Cerbrus** [comment]
*Votes in favor*

**Comment by Canop** [comment]
Note that not *all* RO want to vote. Some just want to follow what happens

**Comment by benjamingr** [comment]
:+1: for votes being more than 24 hours. 72 hours sound good. I also would like to suggest that the voting thread is pinned in the room for the duration.

**Comment by Deathspike** [comment]
+1

Minimum threshold of >= 50% of current RO for addition/removal (based on actual votes in favor or against, non-votes are not counted)?

**Comment by loktar00** [comment]
@Deathspike sounds perfect.

**Comment by RUJodan** [comment]
Agreed on 72 hours and pin.

**Comment by benjamingr** [comment]
Ok, so it doesn't look like @rlemon or @Deathspike 's proposals got any objections and personally I agree with both. 

Are we all cool with:

 - We vote.
 - 50% threshold. 
 - At least 72 hours voting period.

?

**Comment by Deathspike** [comment]
:+1:

**Comment by rlemon** [comment]
I think we need to also non-RO's votes. but we can open a new issue to work that out.

**Comment by kendfrey** [comment]
https://github.com/JavaScriptRoom/culture/commit/9e3ca852d5db7a277ff5022098547d663628d3a6

**Comment by benjamingr** [comment]
Thanks @kendfrey I wonder if it should be left open to discuss when other ROs show up - we literally just agreed that that can take 72 hours of time.

**Comment by phenomnomnominal** [comment]
This is what I'm currently fucked off about. @MadaraUchiha wanted to remove me and @Mosho anyways, that's fine, he has the power. But @ralt just did it with no discussion and that was a dick move.

**Comment by darkyen** [comment]
+1

**Comment by rlemon** [comment]
I really hope no one takes personal offense during these discussions. I don't think owners should be based on personal problems we may or may not have had (speaking in general) rather on how they will actually use the owner tools to keep the room moving forward .. ugh .. peacefully(?).   
If I'm completely off base on 'owner responsibilities' then someone please correct me.
