### ISSUE TITLE
JavaScriptRoom GitHub org

### ISSUE THREAD

**Issue by benjamingr** [JavaScriptRoom/culture#11]
I think all existing owners should be owners of the GH org. 
Currently, it's completely out of sync.

Any objections?

**Comment by MadaraUchiha** [comment]
None by me. Go ahead.

**Comment by Deathspike** [comment]
:+1

**Comment by GNi33** [comment]
:+1:

**Comment by RUJodan** [comment]
No objections, good idea.

**Comment by Jhawins** [comment]
Looks like we need to add just about everyone still

**Comment by rlemon** [comment]
:+1:

**Comment by maniator** [comment]
:+1:

**Comment by Zirak** [comment]
:+1:

**Comment by Zirak** [comment]
Does this also mean we should remove those who are no longer room owners?

**Comment by benjamingr** [comment]
@Zirak no, this proposal does not mean that - although in principle I'm not objected to that. Feel free to make an issue.

**Comment by luggage66** [comment]
:car:

**Comment by Shmiddty** [comment]
:wave:

**Comment by loktar00** [comment]
:+1:

**Comment by Jhawins** [comment]
Could someone resend my invitation. Appearently I didn't get it

**Comment by MadaraUchiha** [comment]
@Jhawins  resent.

**Comment by benjamingr** [comment]
@Shmiddty @Jhawins @luggage66 can you please accept your invitations :)
