### ISSUE TITLE
Issue Visibility

### ISSUE THREAD

**Issue by benjamingr** [JavaScriptRoom/culture#12]
Given our discussions on issue here, I'd like to propose the following:

Issues should remain open for at least 72 hours after the last activity they've had in order to allow discussion to exhaust itself.

Let's vote on it.

**Comment by benjamingr** [comment]
:+1:

**Comment by Deathspike** [comment]
:+1

**Comment by GNi33** [comment]
:+1:

**Comment by ssube** [comment]
Would it make sense to set an absolute minimum (7 days or 72 hours after last comment)?

:+1: either way

**Comment by RUJodan** [comment]
+1

**Comment by Zirak** [comment]
:+1:

**Comment by MadaraUchiha** [comment]
:+1:

**Comment by Shmiddty** [comment]
:+1: 
I vote 1 week, with the ability to override if there is a majority consensus.

**Comment by benjamingr** [comment]
Looks like it's agreed then.
