### ISSUE TITLE
phenomnomnominal

### ISSUE THREAD

**Issue by benjamingr** [JavaScriptRoom/culture#13]
Context: https://github.com/JavaScriptRoom/culture/issues/6

This is a thread to discuss whether or not we should re-add phenomnomnominal as a room owner.

**Comment by benjamingr** [comment]
I think that if Craig is still interested we should RO him again. Except for that isolated incident he's been helpful and constructive for many years and is active in a time zone not many other ROs are active in.

**Comment by AmaanC** [comment]
+1, think he should be RO'd again.

**Comment by loktar00** [comment]
:+1:

**Comment by Jhawins** [comment]
+1 add him back.

**Comment by eeveeta** [comment]
+1

**Comment by funkytaco** [comment]
:+1:

**Comment by Cerbrus** [comment]
No objections. [+1]

**Comment by rlemon** [comment]
:+1:

**Comment by maniator** [comment]
:+1:

**Comment by Zirak** [comment]
:+1:

**Comment by rahul-desai3** [comment]
+1 to add him back.

**Comment by RUJodan** [comment]
HOW DO YOU +1 THUMB

**Comment by kendfrey** [comment]
http://www.emoji-cheat-sheet.com/

**Comment by rahul-desai3** [comment]
:+1:
Thanks @kendfrey!

**Comment by phenomnomnominal** [comment]
:+1:

**Comment by MadaraUchiha** [comment]
:+1:

**Comment by loktar00** [comment]
Honestly I'm sick of having to tell him what deleted messages are, so another :+1: from me.

**Comment by Jhawins** [comment]
Chop chop done waiting, I am adding him

**Comment by Jhawins** [comment]
It's telling me he is already an owner but he isn't.

**Comment by Trasiva** [comment]
:+1: Even if he is a filthy Kiwi, he's our filthy Kiwi.

**Comment by phenomnomnominal** [comment]
closing, cause you all love me and it's done.

**Comment by Cerbrus** [comment]
http://chat.stackoverflow.com/rooms/17/conversation/phenomnomnominal-kicked-towc

We may want to remind @phenomnomnominal  not to play around with those kicks.  
They're not toys.

**Comment by benjamingr** [comment]
@phenomnomnominal - stahp

**Comment by phenomnomnominal** [comment]
Yes yes.

**Comment by Trasiva** [comment]
I think this can be closed. @phenomnomnominal has been good with his powers overall since his return to RO that I've seen and we're past the 72 hour mark.

**Comment by phenomnomnominal** [comment]
I'm amazing.

**Comment by phenomnomnominal** [comment]
FUCK, we clicked the button at the same time.

**Comment by rlemon** [comment]
clearly I got there first. :D
