### ISSUE TITLE
Number of owners

### ISSUE THREAD

**Issue by benjamingr** [JavaScriptRoom/culture#14]
I was thinking about proposing two more owners but I'm a little concerned about the number of owners being a little high.

Is this something that should concern us (high number of owners)?

**Comment by ndugger** [comment]
As long as the current owners are regulars, active, and contribute to managing the room, I don't see the number of owners as a real issue.

**Comment by Jhawins** [comment]
I second that ^

**Comment by benjamingr** [comment]
I third you both

**Comment by Jhawins** [comment]
I second your third to my second

**Comment by ndugger** [comment]
I third your third to my first

**Comment by AmaanC** [comment]
I second all your firsts.

**Comment by maniator** [comment]
@benjamingr I plan on trying to be more active again. Let me know ;-)

**Comment by Zirak** [comment]
As long as they want to be active owners, sure, :+1:.

**Comment by benjamingr** [comment]
@maniator not sure why you pinged me - owners are voted on, if you feel like you'd get in you're welcome to open a new thread about yourself in the repo.
