### ISSUE TITLE
Neal

### ISSUE THREAD

**Issue by maniator** [JavaScriptRoom/culture#15]
This is a thread to discuss whether or not we should re-add Neal as a room owner.

Trying to be more active now and less confrontational than I was when I was more active a couple of years ago.

**Comment by darkyen** [comment]
yes

**Comment by benjamingr** [comment]
:-1: I'd like to see you more active and less confrontational _first_. _After_ I see that for a little while I'll gladly reconsider - but I still remember some things I didn't like from the 2013 period. 

Again, this is about your addition as RO, you know we all <3 you.

**Comment by Zirak** [comment]
:-1:, show change and then I'll reconsider

**Comment by kendfrey** [comment]
:+1:

**Comment by rlemon** [comment]
I think you need to re prove yourself before this is even a conversation.

**Comment by MadaraUchiha** [comment]
:-1: I don't really see you in the room that much. Try to gain some more activity and be more helpful in the room in general. RO is about trust (between RO to RO and between ROs and mods). Try to gain some of both before trying again. I don't think that you can't be an RO in general, just not ready yet.

**Comment by loktar00** [comment]
:-1:

**Comment by Trasiva** [comment]
:-1: I'm pretty regular in the room, and I think I've seen you less times than I can count on both hands.

**Comment by maniator** [comment]
@Trasiva Ha I used to be the most "regular" in the room when it first started years ago.

I have been more preoccupied in recent months with job family etc, etc.

**Comment by rlemon** [comment]
Less fiber maybe?

**Comment by maniator** [comment]
@rlemon fiber is important in a balanced diet you should know that.

**Comment by Trasiva** [comment]
I don't think 449 message constitutes "regular". But either way, start showing up more and contributing, and we'll see what happens down the road.

**Comment by RUJodan** [comment]
:-1: More activity required. Good to have you back though

**Comment by benjamingr** [comment]
Sorry bud, better luck next time.

**Comment by maniator** [comment]
@Trasiva waaaay more than 449 messages man. More like `2896755` (http://chat.stackoverflow.com/users/561731/neal)

**Comment by MadaraUchiha** [comment]
@maniator You have a total of 28970 message in all rooms, and 18.5k messages in the JavaScript room. No one in the network has 2.9 million messages.

**Comment by darkyen** [comment]
@MadaraUchiha hahahaha
