### ISSUE TITLE
Cleanup on aisle org owners

### ISSUE THREAD

**Issue by Zirak** [JavaScriptRoom/culture#16]
Some peeps who are currently [owners of the JavaScript Room org](https://github.com/orgs/JavaScriptRoom/people?utf8=%E2%9C%93&query=role%3Aowner+) aren't room owners. As an extension to #11, the list should be kept in sync, and people who are de-ownered in room should also be de-ownered in the org.

**Comment by benjamingr** [comment]
Sure. 

Not sure if Madara is still an RO, but in case he's not he should still have GH org powers IMO.

**Comment by ralt** [comment]
Definitely feel free to remove me. I tried to remove myself but didn't find out how.

**Comment by MadaraUchiha** [comment]
For easy viewability, we should have every RO with the GitHub [Owner] tag when we post comments. Will be easier to distinguish when voting.

**Comment by GNi33** [comment]
I agree with Benjamin here, I don't know if Mods have automatic Room Owner status (I would guess so), but Madara should definitely have Owner status of the repo, as he's "our" resident mod

**Comment by Jhawins** [comment]
Please complete this whoever is the owner of the Org

**Comment by Zirak** [comment]
This seems to have been done somewhen. I only had to remove Ivo Wetzel.

**Comment by Jhawins** [comment]
![image](https://cloud.githubusercontent.com/assets/4481831/12523434/84799dd6-c11c-11e5-9c10-bd98c27b1c9e.png)

**Comment by Jhawins** [comment]
Per #11 all ROs of the JavaScript room on SO should be owners of the Org on Github

**Comment by Zirak** [comment]
This issue is on the cleanup aspect; there were non-owners who were org owners.

Also, some people chose to keep their membership status private, that's why you don't see them there.

**Comment by Jhawins** [comment]
Makes sense.
