### ISSUE TITLE
Jan Dvorak's room ownership

### ISSUE THREAD

**Issue by Zirak** [JavaScriptRoom/culture#17]
I haven't seen him around the js room in ages. He seems to be active in the Ruby and Haskell rooms, and doesn't mind being de-ownered: http://chat.stackoverflow.com/transcript/message/28283531#28283531

For those of you who don't want to follow the link, here's how it went down:
> Zirak: Hey Jan Dvorak, you are my love my angel, why you treat me like potato?
> Zirak: Also, mind if I de-owner you?
> Jan Dvorak: I don't mind

So I'll remove him since that's his wish, just wanted to lay it bare.

**Comment by benjamingr** [comment]
If he's not interested no discussion needs to be had. Go ahead :+1:

**Comment by rlemon** [comment]
agreed, if he's not interested there is no discussion. Closing this issue, feel free to reopen if he changes his mind I suppose.

**Comment by RUJodan** [comment]
Agreed, he has not been active in the room in mnoths now.

**Comment by Zirak** [comment]
http://chat.stackoverflow.com/transcript/message/28284029#28284029

Now if you follow every link you see you'll have an infinite loop.

**Comment by ssube** [comment]
-1 one of those links took me to youtube.
