### ISSUE TITLE
overexchange

### ISSUE THREAD

**Issue by benjamingr** [JavaScriptRoom/culture#18]
He drops by a lot - never really contributes.

To be fair, usually on topic, but surely a vamp.

How do we deal with him? 

Oh, and he did post some troll pics that one time (hitler etc).

**Comment by rlemon** [comment]
I've been less and less polite as time goes on. Not purposely but he does
ask the same tired questions that lack a Google search first.. Then seems
to dance around the answer you provide for another ten minutes.

Fwiw html room also seems to feel the same. When I'm off mobile I'll look
for sources.

**Comment by benjamingr** [comment]
This is the nazi pic by the way http://chat.stackoverflow.com/transcript/message/28029861#28029861

I wonder if we should just kick him on sight from the room. I wonder if I can summon @Shog9 for an opinion.

**Comment by rlemon** [comment]
In the HTML room he's interacted with BoltClock already (and I can't find him on github :/) -- if you're looking for opinions that is.

**Comment by benjamingr** [comment]
@rlemon Honestly after all these links you posted - I'm mostly looking for a way to keep him out of the JS room for good without us having to kick him on every message :D

**Comment by rlemon** [comment]
but with the current system that would mean locking the room or banning him chat wide.. which seems a bit harsh for a help vamp. I don't want help vamps there, but still seems harsh.

**Comment by MadaraUchiha** [comment]
I feel like publicly shaming one user (however justified) is not a good course of action. If we are going to discuss specific users, please move it to a more private medium.

**Comment by Retsam** [comment]
+1 to @MadaraUchiha 's comment.

**Comment by benjamingr** [comment]
Sure, we can do a private repo.

**Comment by benjamingr** [comment]
@MadaraUchiha I can only create a private repo under _my name_ and not under the JavaScriptRoom org.

**Comment by ThiefMaster** [comment]
You could probably fork your private repo in here. It's kind of cheating but meh, as long as you don't delete your source repo it shouldn't break any rules.

**Comment by ssube** [comment]
That will create a public copy and defeat the point. This might be
something to discuss off of github.

**Comment by ThiefMaster** [comment]
Forks of private repos are also private, and do not count against the number of private repos one can have (which is why you might get in trouble with GitHub when doing that and then deleting the base repo, since it would give you a free private repo without anyone paying for it anymore).

**Comment by benjamingr** [comment]
https://github.com/JavaScriptRoom/moderation/issues/1 good trick @ThiefMaster 
Anyone without access to that thread feel free to ping me.

**Comment by rlemon** [comment]
is there a way to migrate over the current discussion? then maybe delete it from here?

**Comment by benjamingr** [comment]
@rlemon I just did that manually

**Comment by rlemon** [comment]
I see that now :D should we close this then?

**Comment by benjamingr** [comment]
Good idea

**Comment by RUJodan** [comment]
@benjamingr ping -- cannot access link
