### ISSUE TITLE
Teach Me Master!

### ISSUE THREAD

**Issue by ralt** [JavaScriptRoom/culture#19]
@rlemon had [a nice idea last night](http://chat.stackoverflow.com/transcript/message/28290115#28290115): a way for people to do 1-on-1 lessons.

For example, @Zirak wants to learn how to make a baby, so he posts something somewhere saying "Hi Master, Teach Me How To Make A Baby!", and someone knowledgeable enough will pick it, and they'll do a 1-on-1 to teach @Zirak how to make a baby.

Open questions:

- Which platform should we use to put the posts asking for a master?
- Where should the 1-on-1 happen?

**Comment by ralt** [comment]
My answers for the questions:

- I think trello would be a nice idea. Someone makes a card, and someone else can assign it to itself.
- Whatever both participants want. It can be the JS room (if applicable), a private room on miaou, a public room on SO, a hangouts, a skype, whatever.

**Comment by Cerbrus** [comment]
Isn't a good SO question with a good answer much more valuable?

**Comment by ralt** [comment]
@Cerbrus no, we're talking about something that should be done in a chat. A couple of examples:

- How to properly organize my code for this project?
- Can you teach me NAND gates?
- Can you get me a development environment for Lisp?

These kind of questions would be either too broad, too localized, or w/e on SO. They're nice to introduce a chat and discuss about for a while though.

**Comment by Cerbrus** [comment]
Ah, I see. +1

**Comment by benjamingr** [comment]
+1

Just some examples:

I'd love to learn things like:

 - Doing cool data visualizations
 - Writing cleaner UI
 - More technologies

I can teach a bunch of stuff

**Comment by Deathspike** [comment]
+1

Sounds like an interesting idea! It may be worthwhile to record the sessions if it goes by screen sharing and voice so you can share them and teach others, too. That is less personal than the 1-on-1, but if it's a topic another person is interested in *and* want to go beyond the material you covered in that particular session, he can simply ask and do a 1-on-1 that's still interesting for the teacher.

**Comment by GNi33** [comment]
Definitely :+1: 

I think Florian's proposal to manage these on Trello is a great one, the platform seems to be very good on this, one could even decide to teach more than one person then if he feels it's possible for the topic, this can be discussed on the card then and you can add people to the card that want to attend the lesson then.

As for 2, I would not do this in the JS room, it should definitely be a room solely for that purpose. I would probably choose miaou for that, for a wider audience a chat.SO room would probably make sense. 

Reddit had something vaguely similar to this (University of Reddit, intended for a wider audience and with a fixed curriculum that people write beforehand), but the repo seems to be gone.

**Comment by rlemon** [comment]
I'd like to point out that off site things like this die fast. I am for the
teaching being done on so in a separate room whenever possible.

**Comment by ralt** [comment]
IMHO, the teaching should be done wherever the participants want to. No rule there.

**Comment by Zirak** [comment]
This seems like something that happens (or should happen) naturally between regulars (people sometimes ask me stuff, and I sometimes rant at @ralt about lisp, etc). We did have a few people wander in the room "seeking a mentor, a/s/l", but they're usually help vamps.

So if you want to do it, sweet! Not sure it needs to have room regulation.

**Comment by loktar00** [comment]
Agree with @Zirak. Not to rain on anyone's parade There are already sites that do this, such as https://www.codementor.io/, if someone really wants to be mentored and you want to mentor one of the existing services could be used, or do it via hangouts whatever. However I feel like if we have something out there specifically made for this where people can ask for mentoring it will just attract help vamps to that, and the JS room.

**Comment by MadaraUchiha** [comment]
A :-1:  from me as it's currently proposed. This is a sure way of attractive help vampires looking for free mentoring.

I think a bunch of hangouts (or Gallery chatrooms) with one person giving a pseudo-talk about an interesting subject, and others can join in and listen is a better alternative.

**Comment by kendfrey** [comment]
We tried doing talks too, and it was even less successful than the room challenges. I doubt anything structured is going to last.

**Comment by towc** [comment]
+1

Agree with both @ralt and @rlemon: the people should chose what they want if they have a preferred means to do so, but you should reccommend SO for the chatting?
As for what others said on help vamps: we can just tell ourselves not to help anyone until we're sure they've at least tried researching?
And I think that it's necessary to also have a place where you can show what you can mentor in or post your request. A simple application on any of our websites would probably do, right?

**Comment by rlemon** [comment]
> I think a bunch of hangouts (or Gallery chatrooms) with one person giving a pseudo-talk about an interesting subject, and others can join in and listen is a better alternative.

This is exactly what I'm proposing, with the exception that there can be back and fourth. Talks are all fine and well but being able to ask questions in real time is why the chat system works so well today.  

I do **not** think this would increase the number of help vampires, because it isn't really a system for them to vamp on, and if we see it happening we can just remove the post.  All I'm proposing is a system that we can request higher level type things. I don't wanna ask you to fix my code.

**Comment by Zirak** [comment]
But we tried to make talks and I was the only one who actually did something.

**Comment by rlemon** [comment]
I've acknowledged that already. I'm not saying this *will* work, I just hope it will. I see it very similar to talks, but with a spin.  Doesn't matter, I'm putting together software to make the posts on and linking it to github accounts. use it or don't. *:drops mic:* LEMON OUT!

**Comment by rahul-desai3** [comment]
Great idea! :+1: 

> Which platform should we use to put the posts asking for a master?

 - How about raising a GitHub issue asking for a master about `x`? Just saying. This issue can be closed when the master's session is done.

> Where should the 1-on-1 happen?

 - I believe the StackOverflow private chatroom would be great. If both parties agree, they may move to Skype, Google Hangout or the other channels after a quick chat on StackOverflow private chatroom.

**Comment by ralt** [comment]
Sorry, that was a bad idea. Something informal is better.

Thanks @rahul-desai3 for opening my eyes.
