### ISSUE TITLE
Discussion: Mosho and Craig argument

### ISSUE THREAD

**Issue by benjamingr** [JavaScriptRoom/culture#2]
So, Mosho and phenomnomnominal had an argument and acted immaturely - kicking eachother a few times.

Some owners feel like they should be removed.
Some owners don't.

**Comment by MadaraUchiha** [comment]
Remove. Ownership is a privilege, and owners are expected to show maturity. I've seen little from both people under discussion under this thread. Until trust can be re-established, I don't think either of them needs to be a room owner now.

**Comment by Cerbrus** [comment]
I haven't seen the incident.
Can you provide a link for context?

**Comment by Deathspike** [comment]
When was this?

If it was >= month ago it may be appropriate to re-establish both with the promise of showing more mature discussions from now on. I believe in second chances, shit happened, if they are over it now, they are good additions.

**Comment by benjamingr** [comment]
I talked to Mosho and he says he'll behave himself. If you don't trust him to do better feel free to remove him. For what it's worth, what he did didn't harm anyone but the two of them.

**Comment by Deathspike** [comment]
Then I'm in favor of leaving the RO privilege intact.

**Comment by MadaraUchiha** [comment]
@Deathspike It was yesterday.
@Cerbrus It spans over the better part of a day. Mosho was kicked once as part of the new notification detection test, phenom then kicked him again (and for the same reason), and didn't realize that it would be for 5 minutes. When Mosho came back, he kicked phenom back, and then they started kicking each other at random times of the day.

**Comment by Cerbrus** [comment]
That doesn't seem that severe... As long as they got their spanking, I'm sure they got the message.

I'm in favor of leaving the RO privilege intact.

**Comment by benjamingr** [comment]
Ping @ralt - care to share some context?

**Comment by loktar00** [comment]
I assumed they would both be added today anyway honestly. Seemed like it was more of a "cooling off" period for both of them. Overall it was a really petty thing and I don't think they were trying to be overly malicious.

**Comment by ralt** [comment]
@benjamingr what you seem to be missing is that kicking is not "only harmful for both users". They flag the SO team too. We struggled for quite a while until we finally got the kick feature, and now we're abusing it? Yeah, completely irresponsible and they shouldn't be ROs anymore. I'm not saying I don't like them or they shouldn't hang out in the room, quite the opposite. But they shouldn't be given the ROs powers imho.

**Comment by RUJodan** [comment]
I agree with @Ralt here. They knew what the kicking system was, and they still abused it like a toy. Removal. Of course f they prove responsibility add again

**Comment by benjamingr** [comment]
@ralt that's very reasonable. Thanks. I think what @loktar00 said is also fairly reasonable. Should we vote?

**Comment by ralt** [comment]
Sure. I was looking for this link though, so let me paste it now that I found it: http://chat.stackoverflow.com/transcript/message/28212095#28212095

Just to show that it's more than "just both of them".

**Comment by benjamingr** [comment]
I've opened a separate issue for Mosho. When Craig shows up we'll discuss it with him.

**Comment by benjamingr** [comment]
Feel free to reopen
