### ISSUE TITLE
Subdomains under javascriptroom.com requests

### ISSUE THREAD

**Issue by maniator** [JavaScriptRoom/culture#20]
Already have http://culture.javascriptroom.com which forwards to this repo

Make any other requests here.

**Comment by loktar00** [comment]
Not sure if I'm alone in thinking this, please anyone correct me if I'm wrong, but this domain isn't at all officially related to the SO Javascript chat room.

**Comment by RUJodan** [comment]
Seems unrelated as well. Does anybody use jsroom.com?

**Comment by ssube** [comment]
Is there anything on the site that can't be copied to the wiki in this repo?

**Comment by maniator** [comment]
@loktar00 I got that domain specifically for the js room years ago. So yes it is "officially" connected.

**Comment by HorizonShadow** [comment]
That's the domain the rules are on in the description. 

That said, I don't see why the rules couldn't be here.

**Comment by loktar00** [comment]
@maniator yeah I remember when you did, iirc no one asked for it or actually used it.

:+1:  to @HorizonShadow suggestion of adding the rules here, this should be the defacto location rather than having fragmentation.

**Comment by maniator** [comment]
@loktar00 doesnt matter what the context was I got it for this room so we might as well utilize it :-)

**Comment by maniator** [comment]
Wow I did not realize that it has been 3 years. Cool!

**Comment by MadaraUchiha** [comment]
I like the notion of having the rules here. We can make a gh-pages with rules.javascriptroom as an alias. This allows for pull requests and revisions.

**Comment by benjamingr** [comment]
+1 for moving the rules to this repo.

**Comment by Shmiddty** [comment]
@maniator What everyone means to say is that they appreciate what you've done these past 3 years, but it no longer suits their needs.

**Comment by rlemon** [comment]
@Shmiddty :+1:

**Comment by benjamingr** [comment]
@maniator I think what concerns people is the fact that you own the domain so you can choose to do whatever you want with it - so if we start relying on it it gives you leverage. I don't think you'll use the said leverage (I don't think others think you'll use it either) but the _position_ it puts us in makes us feel uneasy.

Like others said we of course appreciate the contribution.

**Comment by Zirak** [comment]
Just FYI, I recently forked the rules repo into this org, it can be found here: http://javascriptroom.github.io/rules/

**Comment by maniator** [comment]
I can hand over the domain to whomever wants to take control of it :-)

Just tell me who to transfer it to.
