### ISSUE TITLE
Pinned messages policy

### ISSUE THREAD

**Issue by FirstWhack** [JavaScriptRoom/culture#23]
Discuss policies for _pinned_ messages here.

Discuss repercussions as well because an RO will be the one responsible for pinning something deemed "un-pinnable"

**Comment by RUJodan** [comment]
Unless the message is harmful, just unpin. Harmful pinned messages, warn the RO who pinned it (hard to do because it doesn't show who pinned what). Otherwise, meh. Never been a huge issue.

If it's something silly, just unpin it. Nobody will care, and if they do... sucks. lol

**Comment by Zirak** [comment]
This seems like another "common sense until isn't" question. Apply common sense. If common sense wasn't applied, question why.

**Comment by Cerbrus** [comment]
+1 for common sense, as @Zirak said.

**Comment by FirstWhack** [comment]
Closing this.

Use common sense with pins
