### ISSUE TITLE
Shmiddty

### ISSUE THREAD

**Issue by Trasiva** [JavaScriptRoom/culture#24]
This guy's an RO, but shows up in the room only every so often, and as of late it seems like it's always to pick a fight or demean someone. It's gotten to the point that every time I see him in the room, it's always the start of something dramatic.

**Examples**
[Here is the latest one between he and I](http://chat.stackoverflow.com/transcript/17?m=28497788#28497788)

[Insulting Cereal](http://chat.stackoverflow.com/transcript/message/28332368#28332368)

[Florian](http://chat.stackoverflow.com/transcript/message/28413168#28413168)

That's just what I managed to pull off his history. If this guy's repeatedly just going to pop in, fire off a few insults and then not say anything else, why is he a RO?

**Comment by ssube** [comment]
None of those are particularly dramatic and even calling them light trolling is a stretch.

I would only question his RO status is he hasn't been active recently.

**Comment by rlemon** [comment]
"I would only question his RO status is he hasn't been active recently." agreed. If anything this highlights how fly-by he has been recently.

**Comment by FirstWhack** [comment]
Shmiddty is a long-term owner. 

In your first message linked he says people in the military are dullards, he is allowed to hold that opinion.
He didn't say "death to the troops", he is saying he doesn't think violence on the scale we commit it is right. He can say that all damn day, it will never become an insult or off limits.

The military comment is the one you're going after, the other links you are just reaching _very far_ for something to complain about.

-1, @Shmiddty stays.

**Comment by rlemon** [comment]
Trasiva, I really hope you didn't just get bullied into closing this.

**Comment by ssube** [comment]
I'm seeing a bunch of discussion (outside of the referenced messages) from late January: http://chat.stackoverflow.com/users/1585400/shmiddty?tab=recent

Looks like enough activity to keep him as RO for now?

**Comment by loktar00** [comment]
I like Shmiddty, but I was thinking the same thing, he is rarely in the room and it's been like that for a while. 

While I like the month rule discussed in another area, not sure it can be a hard and fast rule we always follow. For example if someone stops by 5 days a month, technically it's enough to stay an active Room Owner.. but by no means enough to know whats going on in the room to effectively moderate.
