### ISSUE TITLE
Somekittens ownership status

### ISSUE THREAD

**Issue by loktar00** [JavaScriptRoom/culture#26]
I noticed he was added back to the room owners by Badgercat on Jan 9th. He hasn't been in the room   since December. As the situation stands I vote for his removal as owner.

**Comment by RUJodan** [comment]
:+1: remove. Love the guy but he's not active

**Comment by benjamingr** [comment]
@SomeKittens

**Comment by benjamingr** [comment]
Also for what it's worth we voted and OKd removing ROs after a month of inactivity without voting on it.

**Comment by Zirak** [comment]
I'm :-1: until we get a response from him. If he doesn't participate in this thread or the room in a reasonable amount of time (starting now) then I'll agree.

**Comment by benjamingr** [comment]
Yes, 72 hours

**Comment by rlemon** [comment]
:+1: it appears he is actively avoiding the room. He isn't inactive as a whole. I'm with you Jordan.

**Comment by FirstWhack** [comment]
+1 remove. He is inactive in #17 explicitly yet active on chat. 

Also IMHO, If any other owners are added outside of being tracked on GH they should be immediately removed as well as the RO who stepped outside of the rules until we can resolve the issue.

**Comment by benjamingr** [comment]
@jhawins the last paragraph should probably be a separate thread

**Comment by FirstWhack** [comment]
@benjamingr yeah I went ahead and made a separate thread.

**Comment by Cerbrus** [comment]
Still not active in 17, while active in [8](http://chat.stackoverflow.com/rooms/8/ecmascript)

**Comment by Trasiva** [comment]
:+1: Remove, it's clear he's intentionally avoiding the room while remaining active in other rooms.

**Comment by loktar00** [comment]
Its been 72 hours, I removed him.
