### ISSUE TITLE
Abandon this GH stuff

### ISSUE THREAD

**Issue by FirstWhack** [JavaScriptRoom/culture#28]
I want to quit dicking around and have the room like it used to be. 

We haven't accomplished anything since this GH was started and frankly it's really silly.

**Comment by benjamingr** [comment]
I actually saw a general good trend since we started talking about things. Room felt nicer and people were mostly getting along.

**Comment by benjamingr** [comment]
Also, it already resolved two RO issues fast.

**Comment by Canop** [comment]
I'm not much involved, as you might have noticed, but it looks to me that the GH issue system works pretty well right now for room moderation issues. It's cleaner and better organized than chat discussions, especially than the ones of the JS room, and it's easier to follow.

What's a little worrying, though, is that the SO JS room doesn't seem to be better as a result right now. It's hard to stay there for long.

**Comment by ssube** [comment]
:-1: I agree with Benjamin. This is a great way to record important
discussions, set precedent, etc. I'd like to keep using GH issues.

**Comment by loktar00** [comment]
I like how the discussions don't get lost like they would on the chat. It does a feel a bit more _official_ I suppose so makes it seem weird but idk, still great for historical records.

**Comment by loktar00** [comment]
I'm a nub and submitted early and hit the wrong button disregard my closing :p

**Comment by Zirak** [comment]
@Jhawins What's your alternative?

How can we get the room to "like it used to be" (whatever that is)? What does that even mean? Are we not seeing things which we should see? If so, how does this medium (github issues) stop us, and what other medium fits it better?

**Comment by Trasiva** [comment]
:-1: This keeps things focused and _usually_ takes the hostility out of the room itself, on top of providing historical documentation of issues.
