### ISSUE TITLE
Transparency with private issues.

### ISSUE THREAD

**Issue by loktar00** [JavaScriptRoom/culture#29]
We are a public chat, and I don't think any decisions made behind "closed doors" should stay that way. I understand the comfort of talking privately, but ultimately our discussions and proposed changes have a public impact to the room.

I vote anything private once resolved by the owners, become public and allow other room members to comment if they so wish.

@benjamingr brings up a good point when it comes to private repos not allowing this, so I'm not sure on the technical side how we can make this happen, but I think it would go a long way in showing we are a kinder gentler JS room.

**Comment by Cerbrus** [comment]
:+1:

**Comment by benjamingr** [comment]
I'm for having all decisions that are not about trolls and moderation directly in _this_ repo directly and in the public from the get go.

No need to make these decisions "behind closed doors" anyway.

**Comment by loktar00** [comment]
I feel moderation issues and troll issues could be public as well. Why not? What does it hurt if user Bobmarlynoscopx69 sees we are talking about them. They then get the chance to defend themselves if they feel its warranted.

We still control ultimate access regardless in the room and on GH.

**Comment by benjamingr** [comment]
@loktar00 because someone like the Turkish Nazi gravatar dude would abuse it. That was the point - to not have _actual trolls_ abuse it. I would not have opened that jhawins issue in /moderation personally.

**Comment by Trasiva** [comment]
I thought that was the exact purpose of this repo was for transparency? If there's some secret repo where RO votes are being done...that goes against everything we voted on when we set this up.

**Comment by benjamingr** [comment]
@Trasiva there is a moderation repo that's used for handling with trolls directly - its goal was not to make these decisions in.

**Comment by Trasiva** [comment]
@benjamingr Ah, okay. I'll just duck my head then. I didn't realize we had a separate repo for that sort of thing. Makes sense though.

**Comment by MadaraUchiha** [comment]
I see a couple of problems with a public moderation repo:
1. Trolls - anyone can comment, and when we're discussing people with inherently bad behavior, we don't want them involved to troll the conversation.
2. Users don't like it when their mistakes/bad behavior is publicized (even though they made it public by behaving badly in a chat room). We don't unneeded attention from SO management, and we don't want to look like we're harassing specific users, even if they deserve it.

To clarify: **Only** issues dealing with **specific users** should go to the private repo. **all other issues** should go here, no exceptions.

**Comment by benjamingr** [comment]
@MadaraUchiha I think removing room owners should be an exception

**Comment by Trasiva** [comment]
I agree, the RO removal was where I had a problem. Trolls and whatnot it makes sense to make them unable to add their crap to the discussion.

**Comment by MadaraUchiha** [comment]
If all room owners agree to discuss issues with other room owners here, I don't have any objections. I personally don't mind public discussion targeted at me, and I own all of my actions.

That sounds like a separate issue though, feel free to open it.

**Comment by loktar00** [comment]
@benjamingr  how would someone abuse it? I'm failing to see that I guess.

We have also talked about regulars in the secret repo. Just sayin. Stuff should stay public.

**Comment by MadaraUchiha** [comment]
@loktar00 For example, find the repo discussing their issue and troll it, or flood it with spam.

**Comment by benjamingr** [comment]
> @benjamingr how would someone abuse it? I'm failing to see that I guess.

Flood it with fake GH user comments and other stuff, this is standard in the node repo for example.

**Comment by loktar00** [comment]
Why don't we handle that issue if it comes up, and not preemptively put everything behind a walled garden?

Whats to stop a troll today from doing the same thing at this very moment?

**Comment by benjamingr** [comment]
@loktar00 and I agree - I'm for using `/moderation` only for trolls from this point on.

**Comment by loktar00** [comment]
@benjamingr I can live with that. I think that makes sense.

**Comment by darkyen** [comment]
Why cant RO votes / etc be locked as Contributor only ? And have RO's as contributors to this repo ?

**Comment by ThiefMaster** [comment]
That would also disallow any comments from others

**Comment by RUJodan** [comment]
Closing because innactive
