### ISSUE TITLE
Proposal: Checks and balances

### ISSUE THREAD

**Issue by benjamingr** [JavaScriptRoom/culture#3]
Sometimes owners disagree with the behavior of a proposal of a specific RO about something.

I propose such disagreements should be brought to the attention of other ROs through GH issues in this repo (and not via the other usual alternatives).

**Comment by rlemon** [comment]
IMO, If it is a more serious issue we can take it off-SO, once an initial discussion has been had on SO. I don't like the fact that we're rushing conversations off of the site before they become toxic (when we are unaware **if** they will become toxic).

**Comment by Cerbrus** [comment]
First, try to figure it out one-on-one, in a private SO room.

I've got enough tabs open as it is ;-)

**Comment by benjamingr** [comment]
> I don't like the fact that we're rushing conversations off of the site before they become toxic (when we are unaware if they will become toxic).

I actually kind of like that fact personally.

I'm cool with a private SO room too, but it seems like other owners aren't interested in that since every time I proposed that it was shut down.

**Comment by HorizonShadow** [comment]
I'm of the opinion that disagreeing with a room owner about an action doesn't warrant a discussion. They're a room owner for a reason, and their decisions should be respected, whether you personally agree with them or not.

If a room owner does some action so damaging to the room that it warrants a discussion, the discussion should be whether to remove room owner status from that user or not. 

Just my 2c.

**Comment by rlemon** [comment]
actually, @Cereal, I tend to agree with that.

**Comment by Trasiva** [comment]
I've noticed that probably 90% of all RO actions are genuinely agreed upon after the fact. The only time they aren't, is when someone gets childish after some trolling or an inopportune comment is made. Why does it have to always be discussed afterwards? Generally a comment of "If you disagree, readd" is made, and it usually doesn't get reverted.

**Comment by MadaraUchiha** [comment]
@rlemon  I think you pinged the wrong Cereal there.

**Comment by benjamingr** [comment]
@Trasiva "if you disagree, readd" is how we got to this problem to begin with.

**Comment by Trasiva** [comment]
@benjamingr I've seen maybe two instances of "If you disagree, read" in the last year or so I've been in the chat. Sounds about accurate, no?

**Comment by benjamingr** [comment]
I've seen at least 4. I've also seen lots of cases where ROs disagreed. 

Disagreement is natural - it's not like every disagreement I have with other ROs means I want them removed. Not talking about things is problematic.

**Comment by Trasiva** [comment]
Right, disagreement is natural, and it's going to happen, but forcing a discussion right after a hot button issue happened isn't likely to solve the situation right off the bat. We all have our hot head moments, and telling people to try and have a conversation about it right after the fact isn't going to resolve it. The best option is to leave the communication lines open and let people discuss when they feel it's appropriate.

**Comment by RUJodan** [comment]
I feel like discussions are hurried off the chat too soon. For example, Benji didn't want to discuss the issue this morning in chat, but rlemon was unwilling to go off chat to discuss it. There wasn't really a topic going aside from this, and I feel delegation to a new area excludes other ROs from opinion.

If you can handle being disagreed with (irrelevant to those 2), then you have no business being a RO

**Comment by RUJodan** [comment]
Can't handle*

**Comment by benjamingr** [comment]
@RUJodan I don't like have discussions in the same room because I think it creates a very unwelcoming atmosphere to new users and I want people to know when discussions are made (so for example, a day in advance). That's why I like room meetings and that's why we opened this room. I think it's progress :)

**Comment by darkyen** [comment]
I support @benjamingr the un-welcoming atmosphere can sometimes be too distracting, and the room has a tendancy to derail offtopic as is.
