### ISSUE TITLE
Jhawkins, and the 72 hour rule.

### ISSUE THREAD

**Issue by Trasiva** [JavaScriptRoom/culture#30]
We set up rules for a reason. It was voted upon and agreed with. Anytime a motion is raised to add/remove an RO it's to be brought to a vote with a 72 hour period to ensure that **all** members, not just ROs can voice their opinion. Instead @Cerbrus took a vote in room, a majority of ROs voted yes and @loktar00 removed him. Now, as stated by J, it was a non-issue, but why are we skipping the agreed methods of resolution?

**Comment by benjamingr** [comment]
There was a majority vote in the /moderation repository. 10 room owners have voted to remove jhawins 3 were against and 3 abstained.

It was not a quick vote in the chat.
