### ISSUE TITLE
Jhawins

### ISSUE THREAD

**Issue by benjamingr** [JavaScriptRoom/culture#31]
This issue is to debate @jhawins' room ownership status following the private vote held before in which 10 room owners have voted to remove him, 3 abstained and 3 were against. 

This is a plain vote on whether or not he should jhawins should be a room owner in the JavaScript room.

I'll edit things in as you vote. 
### Votes Jhawins should not be a room owner

Benjamin Gruenbaum
Cerbrus
ssube
Kendall
Cereal
Madara Uchiha
Zirak

**Comment by ssube** [comment]
:-1: Remove.

**Comment by Cerbrus** [comment]
:-1:

**Comment by Trasiva** [comment]
Removing my vote because I just realized it's an RO thing.

**Comment by joshleblanc** [comment]
:-1:

**Comment by kendfrey** [comment]
:-1:

**Comment by loktar00** [comment]
Without context this issue is meaningless.

**Comment by FirstWhack** [comment]
Close issue as irrelevant. The outcome is now irrelevant.

**Comment by tentonaxe** [comment]
I must be missing something... I know there was a disagreement and an argument over the ECMAScript room between two RO's, but... why should that result in a removal of just one of them?

If someone's abusing power, that's one thing, but all I see is disagreement.

**Comment by loktar00** [comment]
@tentonaxe unfortunately it was posted in a private repo so all of the context is hidden. So at this point it looks like anyone who votes :+1:  or :-1:  isn't doing it based on a certain circumstance but just overall feeling, to an outsider at least.

**Comment by darkyen** [comment]
You know what they say about opaqueness in democracy? It kills it!

**Comment by kamlekar** [comment]
You can now react, just saying.

**Comment by loktar00** [comment]
Closing due to 72 hours.
