### ISSUE TITLE
Use Github Reactions feature for votes

### ISSUE THREAD

**Issue by GNi33** [JavaScriptRoom/culture#33]
As of yesterday, Github introduced a "Reactions" feature to PRs, Comments and (as the most interesting for us) Issues, [as described in this blog post](https://github.com/blog/2119-pull-request-and-issue-reactions)

I would propose to use this feature now for any voting process, with only the thumbs up and thumbs down _on the original issue post_ being valid options for a vote. 

The votes would be count directly on the issue - post and votes will not clutter the comment section to leave it clean for further discussion.

What do you think about this?

**Comment by benjamingr** [comment]
This is awesome, are the votes anonymous or named?

**Comment by ThiefMaster** [comment]
hovering a reaction shows the names (and clicking them adds/removes your own reaction for that specific type)

**Comment by GNi33** [comment]
No, they are not anonymous, as ThiefMaster already said. 

This is the only possible downside I could see in this though, because I do not know what happens to the popup when there are a lot of votes and if there is a way to retrieve a complete list of voters/reactions any other way.

**Comment by GNi33** [comment]
Okay, so this is a potential issue:

http://i.imgur.com/yqTx8zE.png

I tweeted to Github if there's a way to retrieve all the reactions, let's see if they respond

**Comment by GNi33** [comment]
Github just got back to me regarding this

> Thanks for writing in!
> 
> That's not possible currently, but thanks for the idea. I have shared it with our team for them to consider.

I'll keep an eye on this and let you know if anything progresses regarding this
