### ISSUE TITLE
Make rlemon revert the !!^ command

### ISSUE THREAD

**Issue by RUJodan** [JavaScriptRoom/culture#34]
This is a serious issue. That monkey is a damned nuisance, and I won't tolerate him any longer! Bring back the arrow!

**Comment by ndugger** [comment]
I demand recompense!

**Comment by ssube** [comment]
The monkey is far superior, unless you can find an adorably fuzzy arrow.

**Comment by RUJodan** [comment]
![up](https://cloud.githubusercontent.com/assets/5186399/13929707/e3b1502c-ef71-11e5-9fd4-7ccf089ae756.png)

**Comment by rlemon** [comment]
![](http://i.imgur.com/glhVKaS.jpg)

**Comment by ndugger** [comment]
![](http://i.imgur.com/9tuMJzD.png)

**Comment by benjamingr** [comment]
Please leave open for 72 hours, I know some ROs ---are in great danger--- care deeply about this.

**Comment by benjamingr** [comment]
Lol not rly
