### ISSUE TITLE
[shameless self promotion] Add my RSS feed pl0x

### ISSUE THREAD

**Issue by SomeKittens** [JavaScriptRoom/culture#35]
Now that I'm on Jekyll, my blog once again has a RSS feed: https://rkoutnik.com/feed.xml

Can has?

**Comment by Trasiva** [comment]
Man, that feed smells from here. :-1:. Just kidding, I'm for it. :+1:.

**Comment by Zirak** [comment]
Done: http://chat.stackoverflow.com/transcript/message/29933271#29933271
