### ISSUE TITLE
MAKE JS GREAT AGAIN!

### ISSUE THREAD

**Issue by rlemon** [JavaScriptRoom/culture#37]
Kevin B for RO.

**Comment by luggage66** [comment]
Object, I do not.

**Comment by Trasiva** [comment]
I can agree to this.

**Comment by benjamingr** [comment]
I have found Kevin to be very reasonable and a positive member of our community. I think he has been around long enough to earn this.

**Comment by ssube** [comment]
Eye. 

He seems mostly sane and mostly smart and that's the most we can ask.

**Comment by benjamingr** [comment]
Gentle reminder about the voting process if anyone cares - this thread will be open for 72 hours after which RO votes for/against count for addition as RO. 

Process detailed here: https://github.com/JavaScriptRoom/culture#room-ownership

**Comment by Canop** [comment]
One more voter and he has a sure majority.

**Comment by luggage66** [comment]
When we spoke of "majority", that was room owners. Some non-RO's voted (which is fine, but it blurs the term "majority").

**Comment by MadaraUchiha** [comment]
We have 10 :+1:s out of 19 owners, do we have an agreement then?

**Comment by tentonaxe** [comment]
well, those aren't all RO's as said previously.

**Comment by Shmiddty** [comment]
Who?

**Comment by rlemon** [comment]
glancing at the usernames, 5/10 are not RO's

**Comment by MadaraUchiha** [comment]
Ah, right, I've mistaken this for the private repo. My bad.

**Comment by MadaraUchiha** [comment]
Fair enough. I've mistaken this repo for the private one. My bad.

**Comment by RUJodan** [comment]
+1 from me

**Comment by loktar00** [comment]
Crap I missed this somehow, anyway +1

**Comment by rlemon** [comment]
if my count is correct that makes 9 owners, and one of them is a mod so he counts for two. so unless there is any crazy objections in the next day welcome aboard Kev. Also please vote (thumb up or down) on the original comment -- counting is much easier that way.

**Comment by rlemon** [comment]
http://chat.stackoverflow.com/transcript/message/33988998#33988998

**Comment by benjamingr** [comment]
@rlemon why do mods count for two?
