### ISSUE TITLE
short-circuiting votes when a majority of ROs have cast their vote

### ISSUE THREAD

**Issue by ssube** [JavaScriptRoom/culture#38]
How do we handle votes when a simple majority of current ROs in good standing have cast their vote?

1. vote remains open for 72 hours (the current rules)
2. vote closes immediately (what I think we've usually done)

The rules leave this somewhat open and I think we should clarify.

Since this is an either-or question, let's say thumbsup is option 1 and thumbsdown is option 2.

**Comment by ssube** [comment]
In my opinion, the first one gives regular non-RO users a better chance to voice their concerns and we should clarify that a majority does not close the election early. If a user has a serious problem, I would like to know, since we are able to retract and change our votes. We're not usually in a hurry, except when removing ROs, and the rules already say they lose buttons pending the vote.

**Comment by luggage66** [comment]
Actually current rules are "remains open 72 hours after last activity", which would exclude any form of early results. I agree with your sentiment, though.

**Comment by benjamingr** [comment]
I think when there is consensus there is no point in dragging the discussion on as it creates drama. In votes that require majority as soon as we have majority we should be able to close.

**Comment by ssube** [comment]
I think when there is consensus, the discussion dies out pretty quickly and doesn't generate any drama. If it's going to be controversial, I'd like to know.

**Comment by luggage66** [comment]
Closed due to inactivity.
