### ISSUE TITLE
Florian Margaine

### ISSUE THREAD

**Issue by benjamingr** [JavaScriptRoom/culture#39]
He was an RO once, I think he did a pretty good job for years helping moderate the room.

He's interested in becoming one again so I'd like to nominate Florian Margaine for room ownership again.

**Comment by rlemon** [comment]
I don't feel the need to vote on this but sure. add him.

**Comment by Trasiva** [comment]
I believe last time he requested it removed, but I'm cool with this.

**Comment by Zirak** [comment]
If he's up for it, then yeppers.

**Comment by MadaraUchiha** [comment]
It's pointless to have this process for room owners who stepped down in good standing and weren't demoted. I've re-added him. If anyone disagrees, open an issue requesting demotion.

**Comment by benjamingr** [comment]
@MadaraUchiha I don't think it's pointless, if someone who stepped down 5 years ago wanted to be RO again we'd definitely vote.

**Comment by RUJodan** [comment]
Yes.
