### ISSUE TITLE
Discussion: Room Challenges

### ISSUE THREAD

**Issue by benjamingr** [JavaScriptRoom/culture#4]
We used to have room challenges, example [here](http://meta.stackoverflow.com/questions/276688/js-room-monthly-challenge-voting).

Is this something we want to try out again?
Would people be interested in having these challenges?
Where would voting happen?

**Comment by loktar00** [comment]
It's not something that hurts, however a very small percentage of users ever participated. With that said no one is stopping anyone from hosting a room challenge if they want. I think that was the last decision made in regards to room challenges.

**Comment by rlemon** [comment]
Smaller == Better.   
I enjoy building larger applications but if it is just for shits and giggles I'll probably lose focus / ambition before long.  
Maybe smaller code-golf like challenges would work better this time?

**Comment by RUJodan** [comment]
I'm all for golf challenges. I never participated in other challenges because I'm so busy. But smal challenges that require clever solutions rather than hours of grinding and hundreds of lines are fun

**Comment by benjamingr** [comment]
Smallest (bytecount) JSX parser -- too hard?

**Comment by kendfrey** [comment]
Who says golfing doesn't require hours of grinding? We want it to be fun, after all.

**Comment by rlemon** [comment]
@kendfrey  I didn't mean to imply that golf challenges were all short. I was using it to indicate a small problem which can be tackled in a relatively small amount of code. I didn't mean we should actually have codegolf challenges (we could, but I didn't mean that).

**Comment by Zirak** [comment]
We gave it a shot, it failed pretty consistently after several ideas, I think it's time we accept that and let go.

**Comment by darkyen** [comment]
How about we just keep a track of usual code-golf, and hop onto challenges from the SO site ? Like bounty questions and stuff ? It will generate rep and usually will be a flow of never-ending challenges people can do on their own free time.

**Comment by Zirak** [comment]
In practice people didn't participate in the proposed challenges and less people participate in code golfs.

**Comment by RUJodan** [comment]
A recent "thing" in the chat has been "the most ES6 way to do X"

For example, what is the most ES6 way to create and iterate a range of numbers.

Those are short, fun, and people seemed to enjoy new wacky ways to make that range

**Comment by benjamingr** [comment]
Yeah, to be fair I'm not sure what I wanted to accomplish in this discussion. If it happens it'll happen on its own. I'm closing now.
