### ISSUE TITLE
Ben Fortune

### ISSUE THREAD

**Issue by rlemon** [JavaScriptRoom/culture#40]
let's end the year off with another RO vote. 

Ben has been active and proven knowledgeable and responsible. He'd also be the third Ben on the RO list. Third times a charm!

**Comment by benjamingr** [comment]
Yeah, sure.

**Comment by loktar00** [comment]
Ben's a cool guy (all of them I GUESS ;) ) good call.

**Comment by RUJodan** [comment]
+1

**Comment by luggage66** [comment]
+0.9999995

**Comment by luggage66** [comment]
We reached majority RO votes. You can see the whole list of thumbs up clickers with:

    curl -H "Accept: application/vnd.github.squirrel-girl-preview" https://api.github.com/repos/JavaScriptRoom/culture/issues/40/reactions
