### ISSUE TITLE
Shrek for Room Owner

### ISSUE THREAD

**Issue by darkyen** [JavaScriptRoom/culture#42]
I'd like to self-nominate myself. I know I had been stupid in past and I have since then matured a lot and am usually active in the JS Room. I believe I should be a room owner again.

**Comment by michaelrwiley** [comment]
I'm kind of an outside observer, but this Vap0r guy is doing good things for the community, maybe look into him for Room Owner?

EDIT: you guys realize that Emoji's hurt right? Who ever this Vap0r guy is he _might_ be crying right now

**Comment by ssube** [comment]
I was under the impression Shrek stopped being RO just due to inactivity. Was there something I missed?

**Comment by Trasiva** [comment]
I'd be okay with Shrek as an RO again. I think perhaps a probationary period of say...one month would suffice. Provided that he remains active.

**Comment by ndugger** [comment]
Stop trying to take advantage of my removal, you bully 😢

**Comment by darkyen** [comment]
I am active, I just don't talk much 😄, I keep an eye on the chat though.

**Comment by luggage66** [comment]
I have no objection but his active period, according to SO, is inline with most of us and we have that time period pretty well covered. That may not be accurate if the other time zones just aren't well represented. Is this a vote or a conversation?

**Comment by darkyen** [comment]
I do work in US Timezones, yes. But I thought there wasn't a top-limit on ROs?

**Comment by ssube** [comment]
There isn't a strict limit, but we don't want all ROs. It's never good for chat rooms and makes getting a majority vote difficult.

**Comment by kendfrey** [comment]
There doesn't seem to be much support for this. No action needed.

**Comment by benjamingr** [comment]
@kendfrey by our rules - he won: 

> Changes to room ownership shall be proposed via an issue on this repository. RO proposals will have 72 hours for voting, after which the proposal will be acted on if 50% or more of standing votes are in favour. 

However, it wasn't pinned. Would you be fine with voting on this after pinning in the room for 3 days @kendfrey ?

**Comment by andkhong** [comment]
hi

**Comment by luggage66** [comment]
I thought votes were started when one of us nominated, not when someone nominates themselves, we talk about maybe starting a vote for a while, then count the votes later when we didn't even know it was a vote.

To quote myself: Is this a vote or a conversation?

**Comment by luggage66** [comment]
In other words, we have enough thumbs up to consider it a nomination, then we should start an actual vote.

**Comment by benjamingr** [comment]
@luggage66 when we had room meetings to discuss this a long while ago we decided to let anyone nominate themselves. That policy isn't set in stone and we can vote on it.

In case whoever nominated the RO is an issue - I would like to nominate @darkyen for room owner so he has someone "on the inside" as a nominator.

**Comment by xbenjii** [comment]
Definitely more active now, what was the reason for dropping RO before?

**Comment by Trasiva** [comment]
He wasn't around. Busy with other stuff at the time.

**Comment by xbenjii** [comment]
Also echoing what @ssube said, how many is too many?

**Comment by luggage66** [comment]
According to #14 there is no hard limit. Wether your vote based on that is up to you, of course.

**Comment by RUJodan** [comment]
+1 vote

**Comment by monners** [comment]
Oh, Darkyen!  +1 for sure.

**Comment by wibily** [comment]
+1

**Comment by loktar00** [comment]
+1 because Darkyen is my homie.

**Comment by ssube** [comment]
+1 aye

I thought we had already voted, so this is all very surprising. :astonished:

**Comment by Canop** [comment]
+1

**Comment by xbenjii** [comment]
Added as RO, it's pretty clear what the outcome is. I know the procedure is 72 hours but this has been open a while and nobody has any problems.

Also can someone close this, because I don't have permission to :)

**Comment by benjamingr** [comment]
@Zirak ^ can you please add Ben to the org?

**Comment by Zirak** [comment]
@benjamingr Doooooooooooooone!
