### ISSUE TITLE
Bring Back The Eyes:Thighs Conversion

### ISSUE THREAD

**Issue by RUJodan** [JavaScriptRoom/culture#43]
Lemon pls!

**Comment by MadaraUchiha** [comment]
wat

**Comment by benjamingr** [comment]
wat

**Comment by rlemon** [comment]
for the uninformed: yesteday jordan said

> i expose my thighs every chance I get

then he laughed to himself for a few minutes and raised the issue to re-implement the listener. 

Jordan, you are a five year old but we love you anyways.

**Comment by RUJodan** [comment]
so is that a yes

**Comment by Zirak** [comment]
On the one hand, that was the greatest thing I ever made.

On the other hand, the greatest thing I ever made was a `s/eyes/thighs/` so you know that ain't saying much.

**Comment by tobq** [comment]
@MadaraUchiha https://meta.stackoverflow.com/questions/355215/unreasonable-suspension everyone help

**Comment by tobq** [comment]
what is "thigh conversations"?
