### ISSUE TITLE
GNi33 for Room Owner

### ISSUE THREAD

**Issue by benjamingr** [JavaScriptRoom/culture#44]
I'd like to formally nominate [GNi33](https://chat.stackoverflow.com/users/809950/gni33) for room owner.

He is a positive influence and a responsible person in the room. He's been with us for 5 years already (more?). He was a room owner before at one point (up to 2014) and was removed at the great purge (when there were problems with the community managers at StackOverflow). 

Now that he's active again - I'd like to vote for reinstating him as room owner.

👍 means yes, 👎  means no - RO votes are binding. Vote ends at Aug 7th at the same time. I'd like to ask all ROs to vote or to explicitly opt out (but that's just a personal request).

**Comment by GNi33** [comment]
Thank you very much for the nomination and the kind words.

I want to add something that I posted to the chat as well that should be taken into consideration I think.
I'm active in the CET timezone, and I am not sure how many active ROs we already have there. 

Additionaly, during the week I'm online pretty much all the time, lots of lurking involved. On the weekends it depends, but usually my SO or nature are keeping me more busy then.

**Comment by RUJodan** [comment]
Hell yeah.

**Comment by Zirak** [comment]
It was surprising to remember you aren't already an RO

**Comment by AmaanC** [comment]
Be warned: GNi33 doesn't actually have pink ice cream on him at all times. 
+1, regardless :D

**Comment by darkyen** [comment]
Definitely an RO.

**Comment by MadaraUchiha** [comment]
I think we have an overwhelming consensus?

On Sun, Aug 6, 2017 at 8:46 PM, Abhishek Hingnikar <notifications@github.com

**Comment by benjamingr** [comment]
@MadaraUchiha no reason to not wait for tomorrow when 72 hours have passed as our protocols suggest.
