### ISSUE TITLE
Rachel Docker, and the silver spoon

### ISSUE THREAD

**Issue by Trasiva** [JavaScriptRoom/culture#46]
I'm curious as to why the hell people are still bending over backwards to help Rachel when she shows up.  She's clearly working on a school project, continues to ask half formed questions, with @benjamingr point blank proving the point by googling and pulling up one of her simplest questions on google as the first result.

At this point she's obviously a very lazy vamp, but somehow still ends up getting rewarded for the bad behavior. Can we just agree to cut her off until she learns how to give an MCVE, put some effort into researching her questions, and actually learns how SO works?

**Comment by MadaraUchiha** [comment]
I don't think it wise to discuss specific people on a public repo. It's a gateway to unpleasantness.

**Comment by benjamingr** [comment]
@MadaraUchiha note that @Trasiva has no access to the RO repo

**Comment by MadaraUchiha** [comment]
@benjamingr That does not void my statement. I am aware that he has no better alternative at the moment.

**Comment by Zirak** [comment]
@Trasiva Thanks for bringing it to our attention.
