### ISSUE TITLE
Gihtub

### ISSUE THREAD

**Issue by tobq** [JavaScriptRoom/culture#47]
Why is this hosted on github, as opposed to something like slack or discord?

**Comment by ThiefMaster** [comment]
Why not? :) Doesn't need a login to read anything, doesn't need a client, almost everyone has a GitHub account...

**Comment by kendfrey** [comment]
There's nothing to discuss or do here, so I'm closing it.

**Comment by tobq** [comment]
You could say the same for twitter

**Comment by benjamingr** [comment]
> Why is this hosted on github, as opposed to something like slack or discord?

It's a platform we all already had, slack is another chat (we'd just open a room) and discord is a whole discussion platform.

If you only need a few issues it works well.
