### ISSUE TITLE
towc for RO

### ISSUE THREAD

**Issue by towc** [JavaScriptRoom/culture#48]
I'd like to nominate myself for Room Owner

I've been a member for a bit over 3 years now, and I've grown to love room 17, especially Kendall's mom. I may not have spilled many goldfish, but you all kind of know me. I do realize there isn't much of a need for new ROs at this time, and there's no "but" to that.
I currently live in the CEST timezone and am online most of the time, I don't think there's much I can argue for or against myself.

Fun fact: I was [nominated by rlemon](https://gist.github.com/Zirak/c5a9ea88b4fc6b8b2164) two years ago, in one of the last room monthly meetings, but [there weren't enough people to vote](https://chat.stackoverflow.com/transcript/message/23336002#23336002) so it kind of just got forgotten

**Comment by MadaraUchiha** [comment]
Please vote on this topic by reacting on the original post with 👍 or 👎 for aye or ney respectively. Only RO votes are binding.

**Comment by Zirak** [comment]
While I do value your contributions to the room in general, one of the things expected of an RO is effectively dealing with evil forces such as trolls and vampires, but that's something I haven't seen you excel at.

Other than that, best of luck to you.

**Comment by benjamingr** [comment]
What @Zirak said - I'd like to see you be more proactive with trolls. I trust you enough as a person and you're a good regular - but you haven't really proven yourself to deal with trolls effectively yet.

I'll pass this one out.

**Comment by xbenjii** [comment]
As above, you seem to join in and exacerbate the trolls, rather than diffusing them. You're a good guy, but I don't think it's time yet.

**Comment by towc** [comment]
meh, I do have a thing for escalating what I consider to be actual problems, and not having much life experience, I'm probably very grey on what a real problem is. It's fair. It's not like I would ever end up using any of the ROs powers unless no other RO was around, which is pretty unlikely.
My main reason for wanting to be a RO is to get a sweet skewed (I won't say italic because... well... yeah) text and the ability to see deleted messages
