### ISSUE TITLE
Bot to notify new discussions under this repo to the room

### ISSUE THREAD

**Issue by MadaraUchiha** [JavaScriptRoom/culture#5]
What do you think? Could be added to cap, or could be done elsewhere.

**Comment by benjamingr** [comment]
Good idea

@MadaraUchiha did you just volunteer? That's awesome.

(btw I think it's possible to just pull the GH rss into the room's feedS)

**Comment by Trasiva** [comment]
Eh, I think if this is going to be an RO thing, it shouldn't notify the whole room.

**Comment by rlemon** [comment]
I don't think it should be an RO thing. Everyone in the room dictates the room culture.

**Comment by MadaraUchiha** [comment]
@Trasiva This repository is public. No point in making it RO only now.

**Comment by Trasiva** [comment]
Okay, I was under the impression it was going to become an RO only thing. But yea, if it isn't, just dumping it through Cap should suffice.

**Comment by kendfrey** [comment]
If Cap pins the new posts, that eliminates a step for us.

**Comment by benjamingr** [comment]
@Trasiva most users in the room are interested in a public and open repo. I think it's a good idea that non owners get to influence the culture too.

**Comment by ssube** [comment]
This definitely shouldn't be RO-only, but maybe don't mirror every comment (to prevent noise)?

New issues and either votes or a 5-10 minute timeout to collect comments on hot issues could be good.

I assume Cap doesn't have a webhook feature, but if that could be a thing, it would make GH and other incoming messages real nice.

**Comment by Zirak** [comment]
We can't (trivially) have webhooks since that requires you to have a url which github POSTs to. "Best" solution to that is raising some server endpoint somewhere which the bot connects to, and the server sends the bot those requests.

Also, repos don't have issue feeds it seems, which is weird since you do have one for commits.

**Comment by rlemon** [comment]
or just use a different bot for it. I have K9 not doing anything and can run on my server..

**Comment by Zirak** [comment]
If K9 runs the headless bot then I may be able to cook something up, I'll hit you in chat for details.

**Comment by rlemon** [comment]
I'm going to work on K9 later today / tonight and see if I can have him report events from this repo. We can play with it from there?

**Comment by Canop** [comment]
I don't have enough time to code it myself but in case it helps I can provide the source of the webhook based bot which sends messages in Miaou whenever an issue in a watched repository is created, commented, modified, etc.

**Comment by Shmiddty** [comment]
:+1: For notifying and pinning on initial creation. 

We need to move Caprica to her own server soon.

**Comment by darkyen** [comment]
How about a simple web task using [Webtask.io](https://webtask.io/) that can be used as a hook (for pretty much anything) that relays the payload of the hook call to a pusher channel. Cap can then subscribe to that pusher channel and act likewise.

**Comment by benjamingr** [comment]
Go for it

**Comment by darkyen** [comment]
https://github.com/darkyen/cap-drone Here is a basic version I hacked in a couple hours, I am talking to webtask team for a better way to save the config / secrets or will update the code (I am going to refactor anyways).

You can point the gh repo hook to 
https://webtask.it.auth0.com/api/run/wt-abhishek-hingnikar_com-0/cap-drone/hook/github/?webtask_no_cache=1

and subscribe with pusher using this

``` javascript
    var pusher = new Pusher('42dcb054493dfec74630', {
      cluster: 'eu',
      encrypted: true
    });
```

It pushes a `hook_push` event with the following dicts for gh

``` javascript
{     
      source: 'github'
      url: 'url that you can link to gh',
      title: 'titl of issue',
      action: 'open|closed|reopened',
      type: 'issues'
}
```

**Comment by benjamingr** [comment]
Anyone interested in picking this up or can I close?

**Comment by luggage66** [comment]
Closing due to lack of interest. Feel free to re-open if you disagree.

**Comment by jbis9051** [comment]
Gonna try adding this to my bot :)
