### ISSUE TITLE
Arrow's status

### ISSUE THREAD

**Issue by towc** [JavaScriptRoom/culture#50]
I'm writing this to escalate the continued negative impact Arrow has had in the room.

It might just be personal, but I don't see it that way. The last major quarrel was on 9/9, starting with [this message](https://chat.stackoverflow.com/transcript/message/39070095#39070095). Vague question, so I tried to make sure he understood what he was talking about, as [he has a reputation for asking about confusing unrelated topics that make you wonder whether he's done any research](https://chat.stackoverflow.com/transcript/17?m=38988776#38988776). The reply immediately comes off as "I'm better than you and I don't appreciate you trying to help me, so go away". As a normal person, I ignore it to make him understand that I can properly help him, and do it in a way that, if responded to correctly, narrows down what his question really is. After one more message, it becomes clear he's unwilling to use any of the information that I'm giving and even googling, which might be fine if he knew his fair share about the subject and didn't want to go on a google hunt, but I don't think he gets to do that. At that point I just ignore his last message because I don't have time for him, hoping he would actually be googling it.

He soon came back with [this very vague message](https://chat.stackoverflow.com/transcript/message/39070294#39070294), missing a lot of context. Luggage comes to the rescue and a fairly civil discussion between them starts, still showing how little effort Arrow is willing to do, and from there [the conversation rapidly degenerates](https://chat.stackoverflow.com/transcript/message/39070400#39070400). Not only do I find [this](https://chat.stackoverflow.com/transcript/message/39070411#39070411) quite offensive and against the spirit of the room, but didn't we decide to kick people using these kinds of abbreviations, after warnings, a while ago? I might be completely wrong, I couldn't find a reference for it.

I will admit to have [responded quite badly](https://chat.stackoverflow.com/transcript/message/39070472#39070472) and there's no excuses for that, but it shouldn't have gotten to that in the first place. It wouldn't be a problem if I was slightly more mature, but by then, an RO should have already stepped in. Then, [this](https://chat.stackoverflow.com/transcript/message/39070533#39070533) tipped me over the top, as well  as [this](https://chat.stackoverflow.com/transcript/message/39070556#39070556), providing more evidence for how little effort he put into reading messages like [my reply to Kendall asking a similar question without accusing me aggressively](https://chat.stackoverflow.com/transcript/message/39070507#39070507) from not very long before.

I'm then not sure where [this almost nice, but not at all](https://chat.stackoverflow.com/transcript/message/39070578#39070578) message came from. At least it felt good because he said I was romanian, and I don't get that a lot in the room ;)

Ben comes in to mitigate, starting with Arrow. I guess he didn't tell me anything because he assumed I was more mature and not at that level of being triggered. Arrow then pings me with semi-apologies that are still meant to clearly imply that it's my fault for all of this, and I do the non-mature thing for assuming he meant his apoligies. I had 3 options: dropping it (which in hindsight is what I should have done), being a dick about it and telling him that I didn't believe it (which is what he did repeatedly), or hoping that he meant what he said, and if he didn't, things wouldn't change much, which seems like a reasonable plan when you have faith in humanity.

The conversation continues in its own head-shaking way until [I get so upset that I just need to take a break and leave](https://chat.stackoverflow.com/transcript/message/39070642#39070642). Yes, this makes me an easy target for trolls, but what I was more angry of (and is the reason this issue exists) was that nobody seemed to be getting involved.

He then comes back today (10/9 european) [asking for more advice on that topic](https://chat.stackoverflow.com/transcript/message/39075591#39075591). I had a night to calm down, and even if he didn't ping me, I don't think I was wrong in providing relevant things to research. Sure, [this could have been worded better](https://chat.stackoverflow.com/transcript/message/39075623#39075623) and it was meant to be somewhat mocking, after he keeps on providing so little information and not taking any apparent steps to help luggage help him (it was fairly obvious that it was what it was, and luggage was clearly not asking about what he answered, but about more details), and the conversation goes on for a while, as I somewhat aggressively keep on providing more useful information for him, and in the meantime I somewhat give up on actually trying to help him knowing that he wouldn't listen, and just keep on sending him the same information he's clearly not trying to understand, I guess because it makes me feel superior, and getting more and more angry as I saw a few members keeping on trying to help him. And that leads to this issue.

After I began writing, he came back with [this comment](https://chat.stackoverflow.com/messages/39076388/history). In other circumstances it would have been fine to ping me 3 times with it, but it just added to my irritation. Again, I don't know where that comment came from. Maybe he meant it, I like to think he did, but it didn't seem to explain how he's been behaving, so I have trouble trusting that.

This was a somewhat detailed commentary of the last things that grinded me up, and while I was never this annoyed by Arrow, there have been quite similar conversation over time, where he just wouldn't listen and keep on asking questions, and everyone reading this probably remembers many of them, so I haven't spent time fishing them from the transcript.

One thing I haven't seen is him contributing to the room in any way. He may genuinely have, and maybe I wasn't around to witness that, but it seems all he's done is using us as toys spooning him with information.

I'm not sure if there are any lessons to learn for people reading this. Surely I have issues myself and I'm working towards fixing them, and while I doubt Arrow will do anything to change his behaviour towards the room, I hope he does.

I'm not asking for him to be banned, although if it was up to me, he would have been. If I had that ability, I would also probably have behaved far more responsibly either way, but I still think it's important for this to be escalated, and to think about every time Arrow and people like him are asking for help

**Comment by luggage66** [comment]
I understand why you would be tired of trying to Help Arrow. Sometimes he seems vampy, sometimes, just confused and/or lost. So.. just don't. You are never required to help or engage with someone you don't want to.

**Comment by towc** [comment]
@luggage66 I don't mean this in a condescending way at all, but I genuinely don't understand why you keep on helping him. That should be none of my business, but by my nature, it's something that makes me really mad. This is again not meant to sound accusatory at all, but can you explain why you do it?

**Comment by ssube** [comment]
I think the links you've chosen highlight your own failings when dealing with people, rather than any problematic trend. I might be one of the most vocal critics of Arrow's code, but I don't think many of those cases are vamping. Posting code and responding to feedback is not the usual pattern.

Public issues targeting a user like this, without any serious claim of breaking rules, are not appropriate and should be closed ([precedent](https://github.com/JavaScriptRoom/culture/issues/46)).

**Comment by kendfrey** [comment]
The trend I've noticed from what you linked here is that he often asks a generic, vague, question that requires some back-and-forth to figure out what he's talking about or trying to do. It's hard for me to fault him for that, since I do the same.

I didn't notice any undue aggression, hostility, or obtuseness. There's a bit of vamping, and a bit of communication breakdown, but nothing really problematic.

He also contributes to the room, even if it's not a large amount. For example, his code helped me learn about combinators composed entirely of the function composition operator, which I thought was pretty cool.

**Comment by towc** [comment]
@ssube well, I'm trying to keep a balanced view while still openly expressing my mind, which is why I criticize myself too. If you were referring to my transcript messages, then I do admit to having a problem, but it came about after repeated cases like these.

If you keep asking questions without seeming to listen, doesn't that count as vamping? And the clearly offensive messages not in good spirit are a fairly obvious violation of the rules

**Comment by ssube** [comment]
I've had a number of meaningful back-and-forth conversations with Arrow, about both [currying](https://chat.stackoverflow.com/transcript/17?m=39044616#39044616) and [DI](https://chat.stackoverflow.com/transcript/17?m=39044616#39044616), so I think your accusations are unfounded and rude.

**Comment by towc** [comment]
@kendfrey comparing me to a broken romanian plate given that context is undue aggression that genuinely hurts because of my famously insecure personality. I do need to grow up, but the users of room 17 shouldn't have to endure that.

As far as your contribution example goes, can you provide a link to the transcript? You may well be right, but I seem to remember that you learnt that while trying to help him on another vamp quest of his, and it lead you to pose a question yourself and learn the answer

**Comment by towc** [comment]
@ssube I'm not doubting Arrow's ability to make constructive conversations

**Comment by kendfrey** [comment]
@towc Re the plate comment, it was possibly in poor taste but not intentionally malicious. His next message was:

> [@towc let it go bro I'm just messing with you.](https://chat.stackoverflow.com/transcript/17?m=39070592#39070592)

**Comment by towc** [comment]
@kendfrey this was my take on it from the issue

> Arrow then pings me with semi-apologies that are still meant to clearly imply that it's my fault for all of this, and I do the non-mature thing for assuming he meant his apoligies

**Comment by ctrldavid** [comment]
@towc I've never seen him post anything remotely worth reading, and he posts a lots of messages. He's the first person I've used the chat's ignore feature on. 

I don't think it's something that's ban worthy though, some people are just like that. I'd suggest ignoring him. It's weird seeing people talking to themselves sometimes, but you're really not missing anything by having his messages hidden.

**Comment by Kamilczak020** [comment]
I disagree as well. He isn't vamping in the full meaning of the phrase, he just seems to not grasp it all. That is probably causing him to get lost and ask a question that appears vague to people who do this everyday, but not to people who are learning and are looking for answers. It's not like he doesn't listen too - I've also seen him working with what other chat members provided and trying to make something out of it - be it clumsily or not. I'm pretty sure everybody has been there at some point, so instead of acting 'aggressive' towards him in chat I'd suggest you point him to how he should do his research and solve problems.

**Comment by towc** [comment]
@ctrldavid there are various known issues with the concept of ignoring itself. While it as an option, it's not one that I'll consider with the current state of things, and that applies to anyone, not only Arrow

**Comment by towc** [comment]
@Kamilczak020 I disagree with your opinion that he's listening. Sure, he has sometimes had some conversations which had nothing majorly wrong with them, but the majority of the conversations I've witnessed were either one-way or were simply discouraging other members from being constructive.

And I've had various previous conversations with Arrow, in which I calmly pointed him to resources and suggested ways to find out how to solve his problem, but one of the reasons I snapped in this last one was because he rarely ever listened. There's a context to this context. It's gone too far

**Comment by ctrldavid** [comment]
@towc I agree with you 100%, having a chat with messages hidden is really shit, it's not something I suggest lightly.  Arrow is the first and only regular I have hidden, and it has genuinely helped make chat more enjoyable to read. 

Having an abrasive personality is not ban worthy (otherwise I'd be long gone) so your only real option is to wait for him to annoy enough people that an issue like this actually gains some traction. At the moment people seem to be content with tolerating him. I'm not, so I hide his messages.

**Comment by towc** [comment]
This message has reached enough people. I think it can be closed for now
