### ISSUE TITLE
Remove Luggage from Room Owners for abuse

### ISSUE THREAD

**Issue by ndugger** [JavaScriptRoom/culture#53]
if I have to go back to find all instances of his RO abuse, I will, but I will simply recall the most recent one.

As you can see from this issue: https://github.com/JavaScriptRoom/culture/issues/52 Luggage had invited another user to return from his kick and ask questions regarding it.

However, when I asked who and why I was kicked for a second time (second time was due to calling out RO abuse on first kick), I was kicked.

Apparently other users are allowed to ask about their kicks except for me. This is hypocritical and an abuse of power.

Kendall seems insistent on the fact that I was kicked a second and third time for claiming RO abuse. This should not be a kickable offense. ***If*** an RO is being abusive, which has happened numerous times from luggage, how is it that I'm not allowed to call it out? That just allows them to continue their abuse.

Abusing your power to prevent someone from speaking up about your abuse of power.

The behaviour in this most recent instance is unacceptable. Other ROs were in on the joke, and they continued to make the same joke after I was kicked, yet only a select few of us were kicked, and with little warning (some, but little).

Afterwards, Luggage said that another user was welcome to return and ask about his kick. However, when I asked about my kick, It was demanded that I stop talking about it, and then I was kicked again. Yes, I've already said that, but I want to drive the point home. This was extremely hypocritical. 

From the words of rlemon,

> honestly, if you feel that way make a new room. we've always helped people with js while joking and memeing

If you are unable to handle joking around, then you need to find a new room, because you disrupt the culture of the room by abusing your powers.

**Comment by loktar00** [comment]
I'm against the way the meme thing was handled but everyone makes mistakes. With that said though I think @luggage66 actually does a pretty good job overall and is pretty level headed. I know there are some long standing issues between some people though hopefully they can be worked out at some point :/

**Comment by ndugger** [comment]
While I agree that I hope things can be worked out, I doubt that will happen due to the constant abuse of power towards me specifically. I don't feel inclined to move towards amenability at this point in time.

**Comment by rlemon** [comment]
for what it's worth, the comment I made that is being quoted was specifically towards Phenomnomnominal and his claim that the room has "turned into an incestuous cesspool of in jokes and bullshit."  

and I still feel that way. If you don't like the culture of the room, you're free to not participate. Jokes and 'bullshit' have never not been a part of the community, and many of the regulars and room owners enjoy the light hearted attitude that is normally going on.   This has been discussed in the past, and it was made very clear that rooms do not need to be strictly on topic 100% of the time.   

I don't need a response to this, I just wanted to make sure my quote is being taken in context.

**Comment by joshleblanc** [comment]
I don't have anything to say on this except that only 2 or 3 of the ROs actually do any moderation (at least that I've noticed).

So it might not be so much abuse, as just moderation in general. (Because of no one's moderating, and someone suddenly does, it looks out of the ordinary).

**Comment by ndugger** [comment]
Maybe we should create an issue of removing all of the other ROs that you're referring to, then. Care to list them out?

**Comment by joshleblanc** [comment]
No, the culture of SO chat doesn't reflect RO = moderator.

It's just happens that ROs have moderator permissions for their specific chat. 

I wasn't trying to imply anyone that doesn't moderate shouldn't be a RO

**Comment by ndugger** [comment]
Then your point is moot. Room Owners are expected to self-moderate the room in the absense of moderators. I see them all doing their duties. I also see Luggage abusing his powers by using his powers far more than he should, especially relative to the other ROs.

He somehow thinks that he gets to dictate room culture all on his own, simply because he's way too fragile and has the ability to enforce his fragility.

**Comment by Cerbrus** [comment]
> He somehow thinks that he gets to dictate room culture all on his own.

Nick, he doesn't. But neither do you.

**Comment by ndugger** [comment]
rlemon agrees that joking around and making memes is perfectly fine. Other ROs and regular members agreed that that's the room culture, yet when Luggage and a couple of other ROs came in and disagreed with the joke, they decided that their version of our culture is more important and decided to kick. 

I'm not dictating room culture, I'm trying to protect it with the other ROs and members that agree.

**Comment by ssube** [comment]
Accusing everyone who moderates you of personal bias and then expecting them to ignore you is judge shopping. If this is just devolving into ad-hominen, it's no longer a serious complaint and should be closed.

**Comment by joshleblanc** [comment]
Perhaps this is relevant: https://github.com/JavaScriptRoom/culture/issues/36#issuecomment-235094886

> Regardless of if this specific kick was warranted or not, I can speak from experience when I say that ssube shouldn't have kicked Filip.
If you're involved in the argument, let someone else handle it.
Someone impartial.

**Comment by ndugger** [comment]
That is very relevant.

Luggage is not impartial when it comes to me, and is incapable of behaving objectively. This is very clear.

The fact that I want to be moderated by an objective party is not "judge shopping", it's common sense.

**Comment by ctrldavid** [comment]
This conversation is quite emotionally charged.  Does anyone have the ability to pull up stats on room kicks? I'd like to see the proportion of ndugger's kicks that were done by luggage vs other ROs.

**Comment by rlemon** [comment]
I wouldn't expect anyone but employees with db access to have that.
