### ISSUE TITLE
Discouraging specific discussions of illegal topics

### ISSUE THREAD

**Issue by ssube** [JavaScriptRoom/culture#54]
This has come up in passing a few times (most recently [here](https://github.com/JavaScriptRoom/culture/issues/52#issuecomment-356759787) and [here](https://chat.stackoverflow.com/transcript/message/40762047#40762047)), but I think we should be somewhat more careful about discussing illegal topics. 

I'm not sure how strict we should be, but I think it's in our best interest not to let folks get too specific. Morally I don't care, but we are all in a publicly-indexed chat, and they could potentially cause legal problems for themselves or others. For example, we actively discourage talking about piracy, but some discussions have gotten very specific about refining and distributing drugs that are not legal everywhere.

I understand that this is probably a matter of opinion and laws vary, but we have binned, deleted, or asked folks to edit messages that could probably count as confessions, and that makes me somewhat uncomfortable. Counterpoints?

**Comment by loktar00** [comment]
> Morally I don't care, but we are all in a publicly-indexed chat, and they could potentially cause legal problems for themselves or others.

Definitely agree with this. In all honesty will anything ever happen? Probably not, but if something does and they go back through logs it would look poorly upon the room, RO's and even stackoverflow as a whole if it looked like people were complacent and allowing it.

**Comment by ctrldavid** [comment]
I'm very much against this. I believe that there is a huge difference between discussing a topic and actually engaging in illegal activity.

**Comment by luggage66** [comment]
I will abide by whatever rules come out of this, and will tone it down some either way, but don't want to limit the ability to talk about, say, thin mints, when we can also talk about beer and cigarettes. 

I do understand it's a public room and not everyone is going to be OK with those topics, so again, completely agree on toning it down, being more discreet, etc. I don't don't like the idea of making it a restricted topic.

**Comment by loktar00** [comment]
I think the issue comes down to people saying they engage in the activity though @ctrldavid, for example people saying they went to their dealer, or that google has logged visits with their dealer.

**Comment by ctrldavid** [comment]
@loktar00 If they want to announce that then that's their choice. It might not be a wise choice, but it's not my place to tell them what they can and can't say.

**Comment by ssube** [comment]
I don't think the whole topic should be restricted, just specific admissions. Going back to [the chat about piracy](https://chat.stackoverflow.com/transcript/message/40762151#40762151), there's a difference between theory and "I did X today and made so much of Y," and that's what can come up later and cause problems.

**Comment by loktar00** [comment]
eh I mean I'm not even pushing for a rule or anything regarding this, I was just pointing out things like this are discussed in the chat, so it's odd to not allow other things that are more tame. Definitely don't want a culture where people feel like they can't talk about certain things.

Except towc and his love life, I'm cool having a rule against that.

**Comment by luggage66** [comment]
Agreed on all counts.

**Comment by joshleblanc** [comment]
I don't see why this should be a hard rule. Soft rule, sure.

I don't think participating in illegal actions should be the main topic of conversation at any point, but if someone mentions it in passing, no harm no foul.

Just common sense, I guess. If someone comes in saying they watched the last jedi through a torrent - who cares. If someone comes in and posts a link to said torrent, not okay.

**Comment by Cerbrus** [comment]
Like ssube said. there's not problem with discussing drug use.

However, encouraging it, or admitting to it is mostly a no-go.

**Comment by ndugger** [comment]
This issue seems to only have been created out of Loktar's pointing out of the room's hypocrisy for moderating lesser issues, like memes.

You want to cover the hypocrisy up by saying, "no look, we're disallowing worse things now too, therefore we can disallow anything else you do because we can."

In this context, I vote against this rule.

**Comment by FirstWhack** [comment]
This has nothing to do with _your_ controversy @ndugger 

I vote common sense rule for drug talk as well. 
This has been a recurring grey area for a few months now.

**Comment by hillimicha** [comment]
I feel strongly on the matter that a **discuss responsibly** policy is applicable, but a 'lighter' version proposed if that makes sense. 

Of course, we shouldn't discuss these things in a manner that advocates committing dangerous or illegal activities.  The discussion typically revolves around the use of 'thin mints' and I think we should be able to discuss it and, in my experience, it has never evolved to the point where we're trading secrets on how to score or sell it.

My next point operates under the assumption as a U.S. citizen, which seems to be a pretty big part of our chat, but I do acknowledge that this gets complicated around the globe.  Given the fact that this is a heavy legal grey area that is changing on a very rapid basis, discussion of thin mints should be treated in the same candid fashion as tobacco and alcohol since we are on a march towards legalizing.  Even during the process, it will become an increasingly large part of our lives so, with that in mind, I disagree with notion that we shouldn't be allowed to talk about it.

**Comment by Cerbrus** [comment]
> Of course, we shouldn't discuss these things in a manner that advocates committing dangerous or illegal activities. The discussion typically revolves around the use of 'thin mints' and I think we should be able to discuss it and, in my experience, it has never evolved to the point where we're trading secrets on how to score or sell it.

Isn't this basically already how these subjects are handled?

**Comment by hillimicha** [comment]
> Isn't this basically already how these subjects are handled?

More or less, it seems, however; the discussion last night in chat seemed momentarily favor the idea of enacting some sort of policy on the form of talking about the topic all together, though I don't think that particular point lasted very long. I wanted to be thorough in my thoughts for the sake of clarity.

**Comment by kendfrey** [comment]
It seems like there is broad agreement here, and not too much has to change. A simple cautionary reminder may be the appropriate course of action.

**Comment by benjamingr** [comment]
Going to close this now, with the consensus on:

> I don't think the whole topic should be restricted, just specific admissions. Going back to the chat about piracy, there's a difference between theory and "I did X today and made so much of Y," and that's what can come up later and cause problems.

and 

> It seems like there is broad agreement here, and not too much has to change. A simple cautionary reminder may be the appropriate course of action.
