### ISSUE TITLE
ROs should ignore users when incapable of being objective

### ISSUE THREAD

**Issue by ndugger** [JavaScriptRoom/culture#55]
It has been made very clear that some ROs are incapable of being objective when it comes to moderating specific issues.

Most recent of which is Luggage (no surprise there).

> @Luggage in as nice as a way as I can put it, I have zero interest in socialising with you and ask that you please don’t try to socialize with me.
https://chat.stackoverflow.com/transcript/message/40763259#40763259

> in as nice of a way I can put it, the feeling is mutual, budy. You've been a real drag ever since you came back to this channel to constantly shit on us and anyone that entered the room. You've openly told us you hate us and we suck and that you like trolling and don't give a fuck about the feeling of others. I gave you room to be nice, but I won't any more.
https://chat.stackoverflow.com/transcript/message/40763268#40763268

His response was obviously very subjective. His last statement is most concerning, regarding "but I won't anymore" -- making it seem as though he's somehow been lenient up to this point (he hasn't), and he suggests that he will kick even more often now.

I was trying to avoid future conflict by asking him to refrain from interacting with me in a social manner. I was not at this point suggesting that he ignore me and refrain from moderating me.

Not to sound like a broken record, but refer to #52 and #53 as to why this is inappropriate

---

I then, after his rude response, suggested that he ignore me in chat, since his behaviour towards me is inappropriate. After I made this suggestion, phenomnominal also made the suggestion that, "[@Luggage and @ndugger probably a good idea if you actually ignore each other](https://chat.stackoverflow.com/transcript/message/40763281#40763281)".

Since there are obviously plenty of other ROs in the room at all active times (ssube was present as well), the idea that non-objective ROs recusing themselves from potentially abusive relationships sounds like common sense to me.

There is also the issue that ssube suggested that I drop it, but then both he and phenomnominal both kept carrying on the conversation; as if they're somehow above their own rules.

If you are unable to moderate a user objectively, either recuse yourself, or step down from RO.

I am not asking to be unmoderated; I am simply asking for you to be the responsible RO that you are expected to be, and rely on the other ROs when you are incapable of fulfilling your role.

**Comment by joshleblanc** [comment]
How can you moderate a chat effectively, if you don't see everyone's posts?

I would argue a RO shouldn't have anyone ignored.

**Comment by ndugger** [comment]
@HorizonShadow while I normally agree; how else would you handle cases where the RO is incapable of being objective? Do you have the other ROs moderate that user instead, or do you ask that RO to step down? I already want Luggage to stand down, but since that seems unlikely, why should I suffer for his inabilities? Having him ignore **one** user will not upset the balance of chat. There are plenty of other ROs to moderate at any given point in time.

**Comment by ndugger** [comment]
In addition, he says that he will not ignore me, seemingly only because I asked him to. It's stubbornness with complete disregard to making peace in the room. He'd rather have more unrest simply so he can remain in control.

**Comment by Cerbrus** [comment]
> I already want Luggage to stand down, but since that seems unlikely, why should I suffer for his inabilities?

Maybe his inabilities aren't as severe as you make them out to be, and the problem is (also) on your side?
Maybe it's not a specific RO's inabilities you're going to have to suffer, but also your own?

You're basically asking ROs to ignore all users they don't get along with.
This isn't about ignoring _one_ user. If ignoring becomes the standard, room owners will get _"just ignore him, you can't be unbiased any more"_ as a standard response for even the most trivial of disagreements.
That's a sure-fire way to completely disable the RO's capability to moderate the room.

**Comment by MadaraUchiha** [comment]
We have a process for that in place, you've been using it for the past day. If you feel an RO has a personal vendetta against you, feel free to point it out.

I'm still, however, not convinced by your explanation, that luggage is abusing his RO powers against you, as are many other ROs.

**Comment by Cerbrus** [comment]
This isn't [the first time that personal vendetta theme](https://github.com/JavaScriptRoom/culture/issues/41#issuecomment-311813065) was brought up.

**Comment by ndugger** [comment]
Because I'm convinced that it is personal. I get more kicks from Luggage than any other RO. The imbalance alone should be a red flag.

Also, I don't have access to the moderation repo, but I've brought up issues with Luggage's abuse in the past, and I'm fairly certain that it was decided that he should let other ROs kick or moderate me because he is "too close to the issue", or something like that.

How is this not the same thing? The fact is is that no other RO kicks me nearly as much or has nearly as much of a problem with me as he does.

**Comment by ssube** [comment]
Despite the quantity of your spamming, your kicks are very few and far between. What reason do you have to believe they're all, or even mostly, from Luggage? You've been asked to stop in chat and here by almost everyone, including moderators.

**Comment by ndugger** [comment]
You're more than welcome to get a log of all kicks done by all ROs.

The fact is that Luggage is offended by far more than any other RO in chat, and makes it very clear when he is the offending RO.

The rule that I cannot discuss my kicks in chat is used as a tool to suppress anyone that you've abused and are unwilling to admit to the fact. We then come to GH issues and the same main folks berate me while I'm defended by a majority.

ssube,
Luggage,
Madara,
Kendall

You four seem to make every issue against me personal. You can claim that you don't, but why is it that the majority of ROs and other room members don't take issue in what I do? Are you four just over sensitive? Do you have a superiority complex? Are the other ROs not doing their jobs?

There is very clearly a discrepancy in how ROs moderate the room, and unfortunately, I'm the latest victim of that.

You need to discuss as a whole how you are going to handle kicks, jokes, memes, and abuse, because right now, there is no consistent set of rules or behaviours from the ruling party.

**Comment by ssube** [comment]
_You_ make every issue personal. Where have you seen a personal attack or any negative comment towards you (that wasn't part of a kick or its follow up)? As far as I'm concerned, it's just spam.

**Comment by ndugger** [comment]
The unbalanced amount of kicks from a very select few individuals is what makes it personal. Majority of ROs do not kick me nor do they take issue with the majority of my actions.

The fact that you see the need to always escalate every little thing by issuing multiple kicks is clearly the problem.

Sure, as far as you are concerned, it is spam, but there were MULTIPLE other ROs in on the joke that were just having fun with it. Are you saying that those ROs are not allowed to make jokes? Do you want to remove any ROs that make jokes in the chat room?
