### ISSUE TITLE
Duggers trolling

### ISSUE THREAD

**Issue by FirstWhack** [JavaScriptRoom/culture#56]
Enough is enough.

Now he is flag trolling. As you can see around the context of this message nothing has even happened... He just picked a out of context message to flag and bring even more attention and drama to the room while he trolls us.
https://chat.stackoverflow.com/messages/40779280/history

**Comment by MadaraUchiha** [comment]
You both got flagged, not sure who exactly flagged you both, but I do believe a moderator other than myself had validated both flags, seeing how both flags had ~2-3 validations when it was approved (usually takes at least 6)

**Comment by FirstWhack** [comment]
@MadaraUchiha  are you saying you validated that lol

**Comment by FirstWhack** [comment]
The topic is Dugger's continued trolling tho, I'm not too concerned about the 30minutes.

**Comment by rlemon** [comment]
@Jhawins  "I do believe a moderator other than myself had validated both flags," so no I don't think he voted on it. My understanding is a moderators vote is binding. so one moderator vote supersedes all regular 10K votes.   

_He_ didn't validate it, but another moderator must have.

**Comment by FirstWhack** [comment]
Thanks for the clarification @rlemon.

Again I'm not _too_ concerned with the _outcome_ of the flag. I'm just tired of an individual user who is clearly the spearhead of this nonsensical drama.

**Comment by ndugger** [comment]
I did not flag you. I did not troll you. This will not be an issue in the future for you, as I now have you ignored.

**Comment by FirstWhack** [comment]
Members feel free to document here as the problem continues, if it
continues. This isn't about me and Duggers interactions.
