### ISSUE TITLE
Kamil Solecki for RO

### ISSUE THREAD

**Issue by luggage66** [JavaScriptRoom/culture#57]
I'd like to nominate Kamil for RO as a generally level headed person that is sometimes on early morning (from the US perspective).

This will remain open for 72 hours. Please vote using thumbs up or down on this message. Everyone can vote, not just ROs.

**Comment by ssube** [comment]
I've had nothing but positive interactions with him, he's been around for a bit and logs in regularly, and generally seems like a bright guy with many relevant interests.

**Comment by hillimicha** [comment]
For what it is worth.  I believe he would be a fine addition to the RO roster.

**Comment by xbenjii** [comment]
Absolutely great guy all around. Level-headed, knows his shit and gets along great with everyone. He also ships me free moonshine 💛

**Comment by Kamilczak020** [comment]
Ooh, thank you very much <3 If you guys are fine with it, I will happily accept ^^

**Comment by luggage66** [comment]
You didn't have a say... :)

**Comment by Shmiddty** [comment]
Shmiddty for supreme ruler

**Comment by Shmiddty** [comment]
Sounds like he wasn't asking for this. Is there a specific reason that he *should* be a room owner? Do we need more room owners?

**Comment by benjamingr** [comment]
Sounds reasonable to me +1, he has been reasonable in all our interactions too and doesn't cause trouble or gets in it. 

> Sounds like he wasn't asking for this. Is there a specific reason that he should be a room owner? Do we need more room owners?

Regulars usually get RO after a certain time if they've "earned" it. We've discussed it before - there is no issue with having a lot of owners as far as I know.

**Comment by Cerbrus** [comment]
Since it seems this [has already been done](https://chat.stackoverflow.com/transcript/message/41322324#41322324), we might as well close this issue.

Congrats, @Kamilczak020. And my condolences at the same time ;-)

**Comment by RUJodan** [comment]
Oh hell no +1

**Comment by Neoares** [comment]
I'm not a RO but I vote yes for the polka  guy

**Comment by MadaraUchiha** [comment]
Well, it seems like we didn't even have to wait the full 3 days to make a decision. Congrats.

Seems like you were already added to the RO group here on GitHub, so I'll just go ahead and close this issue.
