### ISSUE TITLE
Open door. Let's have a discussion 

### ISSUE THREAD

**Issue by FirstWhack** [JavaScriptRoom/culture#59]
I am offering up a dialogue to address the "problem" in a non-chat, unconstrained format.

**Comment by luggage66** [comment]
(speaking for myself only): Today's shit was only about the mod coming in and then us (you.. and me) not dropping it. We don't want the mods taking over shit.

Now.. there is a general feeling of "Jhawins starts shit" that I DO agree with, but not today. There is a feeling that you crap on someone else or dismiss their question or topic as stupid while missing a key point or not understanding the whole story.

Though.. I've also seen you catch yourself and fix this sometimes.

In the past I thought you were 100% troll. These days I think you are only partly troll and mostly misunderstood. I find you frustrating at times (as I am sure you find me), but I like you.

**Comment by luggage66** [comment]
Also, stay away from goats.

**Comment by loktar00** [comment]
You come off abrasive, and I feel like sometimes it looks like you're arguing just to argue. I think over time it just rubs people the wrong way. I had a bunch more written up but @luggage66  beat me to it.

Obviously I like you too, lol but even I remember arguments on the chat we had with eachother before we started working together, I used to think "Jhawins just loves to argue". lol

**Comment by hillimicha** [comment]
Is it fair to say that things got a little tense because the matter of topics getting out of hand and not being stopped when asked is still a bit of a sore spot for people?  I do not believe today's events were reflective of how anyone feels about Jhawin's in particular (certainly not for me anyway), but rather the chat adjusting to new lines that have recently been implemented with the increasing amount of intervention from Mods and room freezes.

**Comment by FirstWhack** [comment]
@luggage66 If I had to guess what you'd say it's pretty close to that. I'm often telling someone something is wrong before he tells me I read it wrong. I noticed that happens a lot when I'm caffeine buzzing.

Now the abrasive part.. Tho it doesn't have to be.
Can I actually fix those things? Partly sure, I strive to, I look dumb when those kind of things happen.
Are they the end of the world or my chat existence if not? Probably not.
Are those things worth writing private GH issues or ongoing discussions of solutions for a problem user?.. Probably not. 


Hoping someone can open my eyes to slightly larger problems as I am -apparently- a problem user who needs to decide if he can change something or head out.

**Comment by FirstWhack** [comment]
@loktar00 I was swearing to you that HDMI 1.4 could run 240hz the other day. You're probably right, I just argue to argue sometimes.

**Comment by luggage66** [comment]
By the way, I saw you asking for dialog about this and wanted to respond. I was trying to think of a what to say that wasn't continuing the conversation like we tell other people not to do..

I'm glad you opened this issue.

**Comment by benjamingr** [comment]
I wasn't involved in that chat today. After reading it I don't think you did anything that problematic.

Also, ❤️

**Comment by benjamingr** [comment]
Thanks for the discussion everyone!
