### ISSUE TITLE
Mosho

### ISSUE THREAD

**Issue by benjamingr** [JavaScriptRoom/culture#6]
I added Mosho back before we agreed it should be discussed (also discussed https://github.com/JavaScriptRoom/culture/issues/2 ).

Context here: https://github.com/JavaScriptRoom/culture/issues/2 
Let's vote on it.

**Comment by benjamingr** [comment]
I vote he stays RO, he's been reasonable for the past year and did mostly useful things. I don't think his friendly banter with Craig had such a terrible impact on the room and he apologized for it. 

I think that we should decide on a policy about kicks but that'll be a separate issue.

**Comment by rlemon** [comment]
I don't think he should be an Owner. Current drama aside,
@Mosho, what do you do that currently requires RO status? how do you utilize the RO tools? I'm often in bed when you are online so I don't wanna assume you do nothing..

**Comment by ralt** [comment]
I vote against for the reasons I outlined in #2

**Comment by benjamingr** [comment]
(Just pointing out that _technically_ since @ralt un-ro'd himself and since he [stated he's not interested in being an RO at this point](http://chat.stackoverflow.com/transcript/message/28230108#28230108) unless we change the rules to count non-RO votes that vote does not count. Discussion of non-ROs voting in a separate issue welcome)

**Comment by Deathspike** [comment]
I believe he should stay on. Yes, there was the "let's try the new tools" rush and that was met with some bad response, but I don't believe that's enough reason to remove RO altogether. Whether or not RO is needed is of little consequence to me, as ROs opinions matter differently from non-RO at this point. Therefore, yes, stay on.

**Comment by Zirak** [comment]
@mosho1 Do you want to remain an RO?

**Comment by darkyen** [comment]
I support mosho too.

**Comment by Mosho1** [comment]
@Zirak not if it entails drama and mandatory responsibilities. I've always regarded RO as elevated regular and will gladly step down if anyone thinks I shouldn't be one.

**Comment by Jhawins** [comment]
Voting is working out hilariously bad.

+1 add him back lets not make this a big thing

**Comment by Cerbrus** [comment]
+1

**Comment by Zirak** [comment]
If he doesn't want owner responsibilities then :-1:.

**Comment by rahul-desai3** [comment]
+1 to add him back.
Shit happens. I believe we should give both of them a second chance.

**Comment by Jhawins** [comment]
@Mosho1 your answer is ambiguous, do you want to be an owner? :P

**Comment by benjamingr** [comment]
Mosho not really interested in being RO. Said he'll remove himself.
