### ISSUE TITLE
Oliver Salzburg RO nomination

### ISSUE THREAD

**Issue by benjamingr** [JavaScriptRoom/culture#60]
I'd like to nominate [Oliver](https://chat.stackoverflow.com/users/259953/oliver-salzburg) for RO.

He's been in the room for a while and more engaged recently. Knows his shit technically, very level headed from my experience and I think he could help moderate. + we have a policy of giving RO to positive influences that stick around.

This will remain open for 72 hours.

ROs and regulars please vote:

👍 for "I'm for adding Oliver as an RO"
👎 for "I'm against adding Oliver as an RO"

😕 ❤️ 😄 or 🎉  mean absolutely nothing.

**Comment by rlemon** [comment]
Be careful when giving Germans power..


Nahh, jk. :+2: from me

**Comment by Kamilczak020** [comment]
I was actually thinking about doing the same!

He has been around for a while, and likely will be a valuable asset. :smiley: 
He also has concrete techical knowledge, which he contributes.

Big +1 from me.

**Comment by xbenjii** [comment]
Big +1 from me, it's about time we got some more eurotrash RO's.

**Comment by luggage66** [comment]
"R O" trash, Euro trash, tomato, tomahto.

**Comment by PheoOneWhoMade** [comment]
+1 Seems like a nice guy.

**Comment by Kamilczak020** [comment]
@luggage66 Battlestar Galactica.

**Comment by benjamingr** [comment]
@PheoOneWhoMade I'll make this very clear. You are not welcome to our community, you are not welcome in the room or in the GitHub organization. 

We have a 0 tolerance for abuse policy, this community is a part of the StackOverflow community which has deleted your account for abuse.

**Comment by ssube** [comment]
:+1: he seems uninterested in most nonsense and I expect the utmost efficiency.

**Comment by rlemon** [comment]
I expect 10% increase in plant discussion and a 14% reduction in 3d printing discussion.

**Comment by ndugger** [comment]
Can we still post memes?

**Comment by ndugger** [comment]
or pictures of zucc drinking?

**Comment by GNi33** [comment]
Absolutely! Big +1 from my side

**Comment by Neoares** [comment]
How can we say no to someone with its own Seal of Quality.

**Comment by FirstWhack** [comment]
Since nobody else -1ed I will be the first.
We don't need regulations and officials, we will build our own roads thank you very much

**Comment by benjamingr** [comment]
> We don't need regulations and officials, we will build our own roads thank you very much

I don't understand that statement @Jhawins

**Comment by luggage66** [comment]
@benjamingr https://en.wikipedia.org/wiki/Anarchy

**Comment by hillimicha** [comment]
Snails are pretty rad.

**Comment by ralt** [comment]
He's not Austrian, so fine by me.

**Comment by rlemon** [comment]
I think this is safe to apply. It's been three days and there is overwhelming support.
