### ISSUE TITLE
Rooms can now be frozen by owners

### ISSUE THREAD

**Issue by benjamingr** [JavaScriptRoom/culture#63]
I found out (by mistake?) that rooms can now be frozen by ROs. You get to it from the `room` menu:

<img width="215" alt="screen shot 2018-05-26 at 19 50 02" src="https://user-images.githubusercontent.com/1315533/40578511-07d0d58e-611e-11e8-91f7-f2f925650fa8.png">
<img width="220" alt="screen shot 2018-05-26 at 19 50 06" src="https://user-images.githubusercontent.com/1315533/40578512-07f2ed86-611e-11e8-8cc3-8d3796ff4422.png">
<img width="827" alt="screen shot 2018-05-26 at 19 50 09" src="https://user-images.githubusercontent.com/1315533/40578513-0812b684-611e-11e8-9d8b-c38544e1fe2b.png">

-----

Questions for ROs:

 - What should our freezing policy be?
 - Who do we notify when we freeze?

**Comment by benjamingr** [comment]
Room owners can keep participating when a room is timed out regularly. Non room-owners get the following message:

<img width="997" alt="screen shot 2018-05-26 at 19 51 58" src="https://user-images.githubusercontent.com/1315533/40578543-52308b1a-611e-11e8-8bed-5bc8dc186077.png">


The number of seconds floats in animation

**Comment by loktar00** [comment]
This is a great feature!

**Comment by kendfrey** [comment]
This has been around for a while now. The general consensus seems to be that it is used for a few minutes for deescalating drama (especially among multiple people), since it's less "extreme" than kicking people.

The downside is that it doesn't affect ROs who may be participating in the drama.

Basically, I see it as a big "Whoa, everybody chill."

**Comment by loktar00** [comment]
@kendfrey TMK RO's could not speak during that time.

**Comment by kendfrey** [comment]
@loktar00 Um what? ROs have always been able to talk during a timeout, afaik.

**Comment by MadaraUchiha** [comment]
This isn't a new feature. Also, it's different from moderators freezing the room in that other room owners can still speak. Be weary of using this feature if other room owners are involved in whatever it is that requires the room freezing.

**Comment by RUJodan** [comment]
This has definitely been around for a while, as I've used it before. If it's a non-localized issue, freeze before kicking is a great move.

If an RO abuses the freeze and continues to make an issue, kick them. If they're still upset? Well that's a separate issue. If you're so upset a room freeze and a kick doesn't stop you, evaluations of power are needed.

**Comment by Cerbrus** [comment]
This announcement has been around for a while now, I think we can safely say that those that need to see this, have.
