### ISSUE TITLE
Mods banned me even when two said more than that

### ISSUE THREAD

**Issue by OGTechnoBoy** [JavaScriptRoom/culture#64]
So, two members were trying to cause a problem with me and shitposting by saying stuff like that I am a troll, idiot, fool and a sexual reference like "We have a new kid to play with"

But I got banned just for saying "idiot" as a self-defense, this is a big misjudgement.

If you ban new members and let old members do whatever they want without getting banned then I'm not proud of being in this room at all.

I don't know who exactly banned me but whoever did that, then he must be the most immature person trying to get attention by using his pathetic mod powers. 

I finished talking here.

**Comment by joshleblanc** [comment]
Link to the discussion: https://chat.stackoverflow.com/transcript/message/43187872#43187872

The message that was flagged proceeded that message, and simply said "Idiot". 

AFAIK he was flag banned.

**Comment by ThiefMaster** [comment]
Yes, it was a flagban.

And since you forgot to mention it, you got another 30min flagban for this message:

> You're an idiot asshole.

**Comment by rlemon** [comment]
>  You're an idiot asshole.
https://chat.stackoverflow.com/messages/43187995/history

Lets not pretend this was as innocent as "idiot" alone.

**Comment by joshleblanc** [comment]
Ah, I missed that bit :)

**Comment by rlemon** [comment]
This was a flagban, meaning the system handled it. I see no reason to leave this issue open. If you have an issue with how the chat flags work you can complain on Meta.

**Comment by oliversalzburg** [comment]
That's very unwelcoming and I'm appalled that this happened.

**Comment by OGTechnoBoy** [comment]
Oh excuse me, I get banned just for self-defense?

Oh of course you do that. Because you didn't see what he said before about me as a sexual reference and that I'm a fool, idiot, troll and stuff like that. Sure you didn't.

**Comment by xbenjii** [comment]
It wasn't a sexual reference. Only an idiot would think that.

**Comment by GNi33** [comment]
Flag Bans are not made by mods or room-owners of the chatroom.

Somebody flagged your message, which means it shows up in a flag queue over all rooms (and even other StackExchange sites). People can review this queue and "validate" your flag, which means they approve of the flag. Once enough people do this, you get kicked.

We've been complaining about this system for quite some time now, but in your case, I think it's fine. Keep your cool.

> Oh excuse me, I get banned just for self-defense?

Fire with fire, eh?
Like I said, nobody in the room kicked you.

**Comment by OGTechnoBoy** [comment]
Then why it didn't happen to them too? I flagged their messages, they started the whole problem. This is just injustice to me.

**Comment by joshleblanc** [comment]
I imagine because no one validated your flags.

**Comment by OGTechnoBoy** [comment]
Wrong. It was a sexual reference so he meant it that way, so he removed it.

**Comment by OGTechnoBoy** [comment]
Oh so no one validated my flags that are more offensive but everyone validated their flags that are even less offensive? That's just a bullshit to me.

**Comment by xbenjii** [comment]
Welcome to SO. Context is everything. Most of the time the +10k users who validate flags won't even come to the room to check the flag. The message appears as a global notification with no context. If they deem it flaggable they'll validate it there and then.

**Comment by OGTechnoBoy** [comment]
Okay. But please don't try to say that they weren't as offensive as I said

**Comment by ThiefMaster** [comment]
> my flags that are more offensive but

Wanna link to any of the "offensive" messages you flagged?

**Comment by kendfrey** [comment]
It's called democracy. Turns out what you said was more offensive.

**Comment by Cerbrus** [comment]
I must say, I wasn't expecting then when I asked you to take any further issues you may have to GitHub.

You got flagbanned. That's because mutliple users all over so chat (not just the JS room) validated a flag resulting from your messages. That's how chat works.

Now, maybe your interpretation of _"We have a new kid to play with"_ isn't in line with what most people think it means. I'm not surprised a flag on that didn't go through.

**Comment by Kamilczak020** [comment]
If you dont like how the 'system' works, I suggest you complain on meta. 
As room owners, we have no power over auto flag bans, other than our personal judgement and flagging (the power of any user).

If you feel abused or weak, I suggest you take this hole case to a mod.

**Comment by OGTechnoBoy** [comment]
Nah, I think I will just close the issue. After all, this is the internet. Coward people say offensive stuff all the time because there isn't responsabilities. Next time, I will try to use this knowledge.

**Comment by rlemon** [comment]
point is that stooping to their level will get you the punishment you wanted for them. Dont do that. 

If you feel towc was being rude, ask a RO or Mod to handle it. Don't start throwing insults around as payback.

**Comment by OGTechnoBoy** [comment]
Thanks for the advices. Issue has closed.
