### ISSUE TITLE
Why I got banned?

### ISSUE THREAD

**Issue by OGTechnoBoy** [JavaScriptRoom/culture#65]
I got suddenly banned for no reason for 24 hours. Explaination?

**Comment by puppystack** [comment]
I'm surprised given the discussion why this isn't remarkably clear to you - I wasn't thinking it'd need to be explained futher.

You were continuing to engage in troll like behaviour despite being asked to stop or even leave. You didn't do either of those. Hence you have a day off to stop such annoying behaviour and time to think through how you're going to conduct yourself in future

**Comment by OGTechnoBoy** [comment]
I hope this is a joke. Which troll behaviour?

**Comment by xbenjii** [comment]
This doesn't really belong here, since the RO's can't ban you for that long. You were banned by a StackOverflow moderator.

**Comment by OGTechnoBoy** [comment]
I'm not kidding. Which troll behaviour?

You don't want to answer because you're such a baby trying to use his mod powers carelessy without any reason. Consider SO is over for me, I should have listened to 1 billion developer that warned me about joining SO instead of just ignoring them and wasting my time here.

**Comment by Cerbrus** [comment]
Okay, I'm going to close this as this is:

1: The result of a moderator action, and as such, not really something we're capable of discussing.
2: Quickly devolving into an undesirable discussion.
