### ISSUE TITLE
Read Only ROs

### ISSUE THREAD

**Issue by 7fe** [JavaScriptRoom/culture#66]
I would like to propose I become a RO RO(Read Only Room Owner).

More importantly I like to stay up to date with issues in the room but not necerrasily sway the chat rooms votes on moderation issues.

 I can stay out of the discussions if need be.  For example these https://github.com/JavaScriptRoom/moderation/issues

Yeah or nah?  I might put it up to vote for RO in 5-6 months but frankly don't want or need the ability to do that.  I am William  on SO.

**Comment by RUJodan** [comment]
No such thing as a RO RO. In my opinion, you've gotten better, but I wouldn't nominate you for RO yet. I see you helping people, but I also see some trolling that could go away (not terrible, like I said you've improved over the years)

What could you contribute to the room, and yourself by becoming an RO?

**Comment by 7fe** [comment]
@RUJodan well it appears it isn't common to just nominate myself so I have closed the issue for now.  Also historically self nominations don't seem to go well.

What examples of trolling are you referring.  I like to joke around but wasn't intending to troll specifically.  I am rather slow so I could see how that comes across as trolling.  I think

**Comment by 7fe** [comment]
Contribute to the room.  Hmm I try to help if I can.  I'm not versed with newer libraries so that limits my helpefulness.
