### ISSUE TITLE
KarelG

### ISSUE THREAD

**Issue by benjamingr** [JavaScriptRoom/culture#68]
I'd like to nominate Karel for RO. They've been around for a while and are a constructive influence in the room.

As always - our policy has been to nominate positive regulars who have been in the room for a while.

👍 for I would like to see KarelG as RO
👎 for I would not like to see KarelG as RO

Anyone can vote but only RO votes are binding.

**Comment by Kamilczak020** [comment]
Yas. Karel is a cool dude, always active in the mornings and helpful to peoples.

**Comment by MadaraUchiha** [comment]
Seems pretty one-sided to me. :tada:

**Comment by KarelGGIT** [comment]
I appreciate the trust that you all are giving to me 😊

**Comment by benjamingr** [comment]
Let's
