### ISSUE TITLE
I'd like to nominate Jhawins for RO

### ISSUE THREAD

**Issue by FirstWhack** [JavaScriptRoom/culture#69]
Hey guys. It's been a long run but I don't plan to leave any time soon.. Do the rules permit me to nominate myself for RO?

I believe I should be an RO in 17 because over the last few years I have proven myself to act in a mature and constructive manner in this room. Most of you presented with this post will know that I have been active here since 2012, with varying degrees of professionalism throughout. I care about not only the long-standing members of this community but also the new-comers, as I believe I demonstrate through my often daily contributions. There is a definite lack of active owners at this time as well as a lack of need for moderator action (I will elaborate on this below). 

If I could give one most prominent reason that I should not be made an RO at this time.. I would simply offer that the room does not need more active moderators right now due to the overall positive culture shift observed over the last 12 months. 

Thank you,
Jhawins

**Comment by Kamilczak020** [comment]
I might not be frequenting SO Chat as much as I used to, but I recall multiple scenarios where you were the start or tipping point of chat drama. 
How do you reflect yourself on that, and, given your history of hastiness, are you sure you will not escalate given the new, moderative tools?

**Comment by Cerbrus** [comment]
> _"because over the last few years I have proven myself to act in a mature and constructive manner in this room"_

And immature and unconstructive, at times.

I'm not convinced that part of you isn't part of you any more.

**Comment by RUJodan** [comment]
@Jhawins Basically being an RO now puts you in line with the Code of Conduct, whether you disagree with it not. Do you find yourself capable of handling situations you may personally find fine, but shut them down because you are able to acknowledge that it's not the right place for the topic?

How would you determine what posts are appropriate versus not, and handle them?

**Comment by FirstWhack** [comment]
It is not about who we are but how we carry ourselves. I have not been a RO
for awhile, I intended to leave the room a year or two ago and I carried
myself accordingly (carelessly). Since some time around The Welcoming I
believe I've demonstrate a clear shift in behavior.

I have definitely been immature and unconstructive at times, as have we
all. I seek to hold an italicised name where I am not permitted to display
such flaws and must drive the community in positive directions wherever
possible, according to the CoC.

**Comment by benjamingr** [comment]
The room is dead and no amount of drama we create will bring it back. You'd be "owning" and "moderating" an empty room.

Thanks for all the fish <3

**Comment by RUJodan** [comment]
@benjamingr the room is just less active, there is very much still activity going on, questions being asked, etc. It's worth lingering around for helping people like the old days, it's just minus the RO off-topic banter

**Comment by FirstWhack** [comment]
Wow. That's an owner right there.

Room's alive until it is frozen and that is that. We are here every day :)
In the meantime I invite you to vote on the current topic, you may not intend to stick around but I and others do. If all of the regulars leave there will be new regs. 

I believe the issue will be open for roughly 60 more hours, it would be nice if someone with current RO status could pin RFC #69 for exposure because at the moment it looks like we only have 7 votes.

**Comment by tentonaxe** [comment]
there's very little need for moderation in the JS room anymore

**Comment by argctl** [comment]
Although I've only been in the room for about a year, it was nice to have Jhawins there, because he served to lighten tensions that I and others may have found contentious. 

It might be easy to say "well don't start drama" or something like that, but we all know it happens regardless of if we want it to, and sometimes it is no one's fault and just a communication issue. Jhawins wasn't in a position of authority at the time, and he still managed to use conversation to step down the conflict in a way that made it more or less humorous. 

Also, having contradictory opinions doesn't constitute "trolling" or "drama", and an RO that understands this is the best RO to prevent drama. Drama and trolling are often spawned from the feeling of being unheard or discounted, and Jhawins, from what I've seen, has never made anyone feel that way. He definitely hasn't made me feel that way while participating in the room even when disagreeing with me.

**Comment by rlemon** [comment]
I don't think we need more ROs.  The room seems to be pretty functional right now, albeit slower than some people may be used too.   

Adding more ROs won't be solving any problems, and doesn't improve the chats.  

We should probably be asking the other RO's who no longer participate to step down if they feel like they will not return.

With that said, I'm not sure if Josiah would make a good RO. Yes he has improved over time, but I still don't think he would make for good conflict resolution. Maybe I just need to interact more with him now tho, but as of right now my vote is a no.

**Comment by FirstWhack** [comment]
I do largely agree. Honestly I'm not super concerned with being a RO or
not. I really just want to put forth that I like this place, I'm glad to be
a part of it and that it still exists. This is such a unique community even
in it's current state.. I've never seen anything quite like it. I'll be
here to stay regardless and I hope the room continues to stay out of the
negative spotlight.

We've helped so many people including myself.

**Comment by forresthopkinsa** [comment]
FWIW I think Josiah has grown to be a lot less incendiary than even just a year ago. I've seen him exercise some tactful conflict resolution lately, even though that hasn't really been his responsibility as a non-RO.

More importantly, he's one of the most active members in the room. He's very consistently online during U.S. daytime, which is when a lot of the room's remaining activity is.

As for whether the room *needs* another RO, well, I don't really know about that. It seems to get along OK. But if someone is going to take up the mantle, I think he makes the most sense.

**Comment by jakeNiemiec** [comment]
> @rlemon I still don't think he would make for good conflict resolution.

Your personal conduct seemed to push people out of the room (including myself). **As long @Jhawins is willing to put in the work and show the personal responsibility required**, who are you to stand in the way?

*Edit*: @tentonaxe My point is that lemon has a bad track record for conflict resolution (some instances bordering on power-trip moderation). But my experiences are from last year before the rule changes.

**Comment by FirstWhack** [comment]
I did not see the edit on your post @rlemon. I had reacted to the original text.

**Comment by tentonaxe** [comment]
> who are you to stand in the way?

He's a room owner, and room owners get to vote on who gets to become a room owner. If you have a problem with that, open a separate issue.

**Comment by RUJodan** [comment]
@jakeNiemiec your history with @rlemon has no place in this vote, and you most definitely cannot try to use it to de-value his vote. It doesn't work that way

**Comment by rlemon** [comment]
@Jhawins  as hard as this will be to sound sincere, I really did not mean that as a dig. Just that you have a history of adding to the conflict versus resolving it. I did say you have changed, and that maybe I just don't talk to you enough recently to fully embrace the new you. So please don't take offence to it (again, I know how that doesn't work), It's just how I feel about your RO nomination as of right now.

**Comment by FirstWhack** [comment]
No offense taken. That is what this thread was made for.

**Comment by Canop** [comment]
> We should probably be asking the other RO's who no longer participate to step down if they feel like they will not return.

I'm perfectly OK with stepping down and letting my position to users who are more involved than me and are a much bigger part of the room's culture.

Should I create another issue for that ?

**Comment by KarelGGIT** [comment]
I am having two thoughts: We all know that Jhawins has a reputation. There were moments in the past that the chat got locked while he was active and using the chat. Yet everyone deserves a second change. However, when we look at the state of the SO chat, we can see that its activity is not what it has been like before. (I admit that I miss some regulars there 😔 . Not to mention those funny moments. <# for all)

As rlemon pointed out; we have plenty RO's now that covers most times in the chat. I would not mind to put your candidate on the shelf for a while until the room becomes more active or that there is a need for other RO's to support the current RO team.

**Comment by FirstWhack** [comment]
Well we got a lot of votes, surprisingly even from some of the room's now "ex" followers (they'll always be back!).

Owners yes:
Luggage
BenFortune
Madar
Shrek

Owners no:
Kamil
Cerberus
Rlemon
Copy
KevinB

That's 4 yay to 5 nay.
Topic closed


Non-owner voters (lol):
Towc
Loktar
DavidKamer
Trasiva
Forresthopkinsa
JakeNiemiec
HilliMicha

**Comment by luggage66** [comment]
Historically, non-owners also get a vote.

See the first messages on:
https://github.com/JavaScriptRoom/culture/issues/57
https://github.com/JavaScriptRoom/culture/issues/30

**Comment by tentonaxe** [comment]
https://github.com/JavaScriptRoom/culture#room-ownership

> Changes to room ownership shall be proposed via an issue on this repository. RO proposals will have 72 hours for voting, after which the proposal will be acted on if 50% or more of standing votes are in favour. Exceptions will be made for ROs that are clearly vandalizing or damaging the room, in which case they can have RO status removed immediately, to prevent further damage.

**Comment by luggage66** [comment]
More relevant than my last links. Discusses non-RO voting specifically: https://github.com/JavaScriptRoom/culture/issues/38

... kinda

**Comment by FirstWhack** [comment]
So the conclusion is that Non-RO votes do count? What about random users on GH, anyone could vote at that point and it would be hard to decipher.

**Comment by joshleblanc** [comment]
Non room owner votes should count.

Vote manipulation is easy enough to notice.

Room owners are a small subset of room users, and new room owners affect all users so they should have a say.

**Comment by FirstWhack** [comment]
Well... At the 72 hour mark this was 9-5 Yay:Nay, it seems more Nos are accumulating even now. 

The ball is in the existing ROs court as to what to do on this one. 
We should also present these in a more public manner when pinning in the room from now on. "ROs :#X" is not a way to invite non-RO users to vote.

The nominator (if not an RO) should also probably not be the one responsible for closing/tallying/resolving the nomination. I did my best tho.

**Comment by Trasiva** [comment]
All I have to say is 

> Lol, afk

**Comment by loktar00** [comment]
The primary reason I voted no was due to The Welcoming and Gamergate issue which both required SO admin intervention and had pretty dire consequences for the chat, both involved @Jhawins. They were mostly a case of wrong place wrong time, however if Twitter caught wind of the fact one of the people who was responsible for the "unwelcoming" in the JS room was now promoted to an owner it might not be perceived in the best way.

The chat is definitely just a shell of what it was as most of us have moved elsewhere for day to day communication so why would it require more moderation? If anything @benjamingr assessment seems the most accurate. @tentonaxe seems to be doing a great job moderating the day to day, and @rlemon, @RUJodan, and @kendfrey jump on pretty frequently still. ROs were generally added when there was a need, what caused this need? When was the last time a user was even kicked?

**Comment by Cerbrus** [comment]
> Historically, non-owners also get a vote.
> 
> See the first messages on:
> #57
> #30

@luggage66: That second link you posted also says this:

> There was a majority vote in the /moderation repository. 10 room owners have voted to remove jhawins 3 were against and 3 abstained.

RO votes outweigh "member" votes here. Otherwise, we could have a bunch of random users from another channel come in and decide one of them should be a RO.
