### ISSUE TITLE
How will we handle voting?

### ISSUE THREAD

**Issue by kendfrey** [JavaScriptRoom/culture#7]
Leaving +1 or -1 comments is a valid voting system, but it's not a good system. We should have a good voting system.

Requirements:
- Allow "for" and "against" votes, one per user.
- A user can change or retract their vote at any time, erasing the previous vote.

**Comment by benjamingr** [comment]
I think we should try GH +1 and -1 and if it doesn't work move to a different system.

**Comment by loktar00** [comment]
:+1: to @benjamingr  suggestion

**Comment by MadaraUchiha** [comment]
:+1: @benjamingr

**Comment by Zirak** [comment]
:+1:

**Comment by Cerbrus** [comment]
:+1:

**Comment by benjamingr** [comment]
Closing as it is working out so far - if it ever becomes a problem let's revisit.
