### ISSUE TITLE
Denys has no business being a RO

### ISSUE THREAD

**Issue by Canop** [JavaScriptRoom/culture#70]
He does nothing, rarely visits, and isn't really part of the room culture.

Let's remove his RO status so that more active users can be nominated instead.

**Comment by FirstWhack** [comment]
Aren't YOU Denys???

**Comment by tentonaxe** [comment]
I was gonna respond with a snarky response saying you could remove yourself, but, now that I test that theory, it doesn't seem to be an option. Stepping down of course doesn't require a vote

**Comment by tentonaxe** [comment]
Ah, you can, you just have to go to control access.

**Comment by Canop** [comment]
> Stepping down of course doesn't require a vote

I'm not stepping down. I'm OK for being a RO. But as I'm obviously not the best fit, I raise the issue so that you can vote for it and demote me (I'm also totally OK with not being a RO anymore).

**Comment by RUJodan** [comment]
The way I see it, we don't really kick inactive ROs (especially legacy reasons). There's no quota for RO slots, so it's not like you're blocking anybody from joining :) You've definitely earned the right to keep the italics even if you rarely get online lol

**Comment by Cerbrus** [comment]
The consensus appears to be: Meh, there's no need for the removal.

Considering the lack of votes in favor of removal, I'm closing this issue down. :-)

**Comment by Canop** [comment]
ok
