### ISSUE TITLE
Tom Minor as RO!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by ghost** [JavaScriptRoom/culture#71]
My SO profile:
https://stackoverflow.com/users/7437719/tom-minor

EVERYONE VOTE FOR TOM MINOR AS ROOM 17 RO!!!!!!!!!!!!!!!

**Comment by ThiefMaster** [comment]
![](http://giphygifs.s3.amazonaws.com/media/amxLHEPgGDCKs/giphy.gif)

**Comment by xbenjii** [comment]
Yeah... no thank you.

Especially since you're currently suspended.

![](https://xbenjii.co.uk/i/7381d12b12be)

**Comment by ghost** [comment]
@xbenjii HOW DARE YOU MAKE A FAKE PICTURE

YOU USED IMAGE EDITING SOFTWARE OR SOMETHING ELSE

**Comment by Trasiva** [comment]
I'd rather have my fingernails pulled out slowly by a weak toddler than consider you for RO.

**Comment by ghost** [comment]
@Trasiva you do not even know who i am one little bit so you have no leverage or say and therefore also dont know if i would be a good ro or not

**Comment by RUJodan** [comment]
No

**Comment by Cerbrus** [comment]
Considering that you've yet to make a positive contribution to the room, and your habit for getting banned from chat, There's no point in discussing this.

> [![image](https://user-images.githubusercontent.com/2911988/69029115-50b55800-09d4-11ea-939a-7b5fe8cc060f.png)](https://chat.stackoverflow.com/users/7437719)

<sup>(This image links to his chat profile)</sup>

**Comment by Cerbrus** [comment]
Context for his current chat suspension [here](https://chat.stackoverflow.com/transcript/message/47839234#47839234)
