### ISSUE TITLE
@JamesBot Room Owner Access

### ISSUE THREAD

**Issue by jbis9051** [JavaScriptRoom/culture#72]
Hi!

Since @rlemon and his bot, Cap, have left the room, [JamesBot](https://stackoverflow.com/users/11518920/jamesbot) has replaced Cap as the main bot. Most of the functionally has been copied over including the [auto welcome](https://chat.stackoverflow.com/search?q=welcome&user=11518920&room=17), [detecting unformatted code](https://chat.stackoverflow.com/search?q=unformatted&user=11518920&room=17) as well as fixed features like the [mdn command](https://chat.stackoverflow.com/search?q=mdn&user=11518920&room=17).

To help with moderation, I propose adding JamesBot as a RO as Cap was. This will allow unformatted messages to be moved to the trash and allow for greater moderation functionality in the future.

**Some information on the bot itself**: 

JamesBot is open source and [on Github](https://github.com/jbis9051/JamesSOBot). I can add RO's as contributors to the repo so they can add commands and fix things as they see fit. Testing can be done in [this room](https://chat.stackoverflow.com/rooms/193540/test-my-bot) (or in the sandbox). I have also given RO's permission on the bot to disable it and ban people from using it as necessary. I am currently working on an import script to import all the learned commands from Cap. The bot runs off of my home server. Unlike Cap, it does not run in a browser instance. Instead it runs in a node instance. This reduces overhead.  Eval is done using a combination of Cap's (Zirak's) whitelist eval script as well as the [isolated-vm module](https://github.com/laverdet/isolated-vm) for secure evaluation. We (me and some of the other regulars in the room) are still working on even more secure evaluation. Included in the repo is also [unofficial documentation of the StackExchange Chat API](https://github.com/jbis9051/JamesSOBot/blob/master/docs/CHAT_API.md).

If anyone has any questions about the bot itself feel free to ask! :) Also feel free to open issues or PR's on the repo.

Thanks, 
[@JBis](https://stackoverflow.com/users/7886229/jbis)

**Comment by tentonaxe** [comment]
I think in this case, this is more than just a vote for RO access for a bot, it's a vote for RO access to both the bot and the person running it... because at that point they are an RO, as they own/control both accounts. It doesn't really make sense in my opinion to do one without the other.

**Comment by tentonaxe** [comment]
That said...

I don't think moving poorly formatted code to the trash is as important as it used to be, due to how little activity the room gets now.

**Comment by jbis9051** [comment]
@tentonaxe I think you make a very good point here. By giving RO to the bot user your are effectively giving me RO. However, I would like to point out an important distinction between my user (@JBis) and bot user (@JamesBot) getting RO.  

As I see it, voting for someone to become RO comes with two main components. You trust that person not to abuse their power and also that they will be an effective and fair moderator. They are there to help settle disputes if they arise and have the power to kick someone and even disable to room temporarily if necessary. 

By voting only for Jame's user (and not me) to become RO, you are trusting that I won't abuse the power of RO through Jame's user. However, it does not mean (or at least I don't see myself this way) that I have any more authority than a regular user.  I am equal to a non RO user. Assuming you trust me not to abuse my power, I see a distinction between me being RO and James being RO.

That being said, with the loss of a couple ROs, I am willing to become a RO. I am not sure if other RO's want that. Most of the people voting on this have will have interacted with me at some point and have seen me interact with others so I see no reason to explain why *I think I would be a good RO*. That is for you all to decide.

**Comment by forresthopkinsa** [comment]
+1 for James and Josh being distinct users that I don't expect to overlap. I say we make an existing RO (Kevin?) a joint owner of the James [repository](https://github.com/jbis9051/JamesSOBot) and account credentials, to discourage abuse.

I don't really think we need any new _actual_ ROs; whenever there's a problem, it's easy enough to ping someone else to take care of it. But I did encounter someone post unformatted code that James caught but couldn't do anything about (and was therefore left unchanged) within the last hour. It's annoying.

**Comment by tentonaxe** [comment]
Giving me access to the repo wouldn't do much, i'm too lazy for that to make any difference, bsides, ownership of it isn't required to see/monitor it.

**Comment by benjamingr** [comment]
Honestly the RO list needs an overhaul anyway and anyone not active in the last 2 months should be removed. I would be fine with stepping down as well if people want me to and new people (the ones active now) should take charge of managing the community. 


As much as I would love to have Octavian/Jan/Denys/Ben/Eva and the rest of the gang active that ship has sailed years ago and we old folk should make way for new leadership.

**Comment by Canop** [comment]
I already said that I have no objection in being removed if it seems I'm in the way of a new leadership.

The new leadership of SO made me stop answering questions already...

**Comment by SaitamaSama** [comment]
Sounds something like what a Boomer would say!
😛

**Comment by Canop** [comment]
Hey... I'm not **so** old!

**Comment by ikariiin** [comment]
lmao, I misrecognized the issue I was commenting to, but glad you took it in a fun way.
😄
shouldn't have deleted that comment either now that I think of it, mb :P

**Comment by forresthopkinsa** [comment]
We should open a new issue for the topic of New Management. I think we can safely call this proposal separate from that (much larger) one.

**Comment by tentonaxe** [comment]
I went ahead and made this happen since no one opposed it, feel free to open another issue if this needs to be revisited.

**Comment by jbis9051** [comment]
https://chat.stackoverflow.com/transcript/message/48034105#48034105
