### ISSUE TITLE
Adding "HTML / CSS / Web Development" to our title and scope description

### ISSUE THREAD

**Issue by jbis9051** [JavaScriptRoom/culture#73]
Hi everyone!

As most of the people who are still visit the room know, the room is not as active as it used to be. This makes me sad :( 

So I have been thinking about some possible ways to increase activity! I was thinking we could possibly add "HTML / CSS / Web Development" to our title (`JavaScript (and HTML/CSS/Web Development`). 

We already answer many web development questions outside of JavaScript so the room discussion itself wouldn't change but it would at least make it easier for people seeking web help to find us. Based on the current title and description, it seems that the discussion is limited to JavaScript.

I understand that [HTML / CSS / WebDesign ](https://chat.stackoverflow.com/rooms/29074/html-css-webdesign) exists but I figure we can possibly combine.  Even if they don't shutdown that chat, I don't see a problem with similar topics for two chats.

I'm not 100% sure about this so please, lets discuss!

----

**P.S.** I know there are a bunch of old RO's and old members who left for various reasons (who might still see this post) whether it be work, people reporting you on twitter/flagging, or in protest of StackOverlfow's recent issues. I ask that you come back. Even if you drop in during work for a couple min to say hi! We haven't had twitter or flagging issues in a pretty long while. And we love discussing how annoyed we are at SO. So come join us!

**Comment by Canop** [comment]
I don't really like that:

The guys at HTML/CSS/WebDesign are (were?) good guys I like.
But what made for me the JS room interesting was the possible discussion of deep technical JavaScript points, not really all-encompassing web help. It should stay as focused as possible IMO.

Regarding your PS. I'm not sure SO is still enough existing to be the right place to discuss how dead it is.

**Comment by Afif13** [comment]
*I don't see a problem with similar topics for two chats.* --> I do. Why overflowing one chat with a lot of topics. Even if the HTML / CSS room isn't that active we are still interacting with some users and helping them with their HTML/CSS issues and we advice the JS room for JS stuff

**Comment by joshleblanc** [comment]
>  Why overflowing one chat with a lot of topics.

The js room isn't even overflowing with 1 topic

**Comment by Tyler-H** [comment]
If room 17 wants to add HTML, CSS, and Web Design to their room title and approved/supported topics (though I don't think such questions are explicitly _disallowed_ there currently), the ROs are of course welcome to do that. We won't be shutting down room 29074, though.

**Comment by Cerbrus** [comment]
I don’t think it’s a good idea to add that to the “official” topic.
As mentioned, it’s not forbidden to discuss those topics.

**Comment by jbis9051** [comment]
@Cerbrus  Why not?

**Comment by Cerbrus** [comment]
Because there’s another room out there that already has the subject covered.
I’d rather see users with questions about HTML enter that room, than to get into 17, as they’re more likely to find the answers they need, there.

**Comment by jbis9051** [comment]
This proposal has been voted on. The final vote is 3 up votes and 8 down votes.  The proposal does not pass.
